from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager


class EniUserManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        """
        Create and return a regular user with a username and password.
        """
        if not username:
            raise ValueError('The Username field must be set')
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        """
        Create and return a superuser with a username and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(username, password, **extra_fields)

# Create your models here.


class eniUser(AbstractUser):
    username = models.CharField(max_length=20, unique=True)
    email = models.EmailField(max_length=40, blank=True)
    fun_tipo_iden = models.CharField(max_length=30, blank=True)
    fun_sex = models.CharField(max_length=10, blank=True)
    fun_titu = models.CharField(max_length=40, blank=True)
    fun_esta = models.IntegerField(default=0)
    fun_admi_rol = models.IntegerField(default=0)
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    objects = EniUserManager()

    @classmethod
    def get_all_users(cls):
        return cls.objects.all()

    # def nombre_completo(self):
    #     return self.first_name + " " + self.last_name

    # def __str__(self) -> str:
    #     return self.nombre_completo()


# Crea la tabla de Unidad de Salud
class unidad_salud(models.Model):
    uni_zona = models.CharField(max_length=10, blank=True)
    uni_dist = models.CharField(max_length=8, blank=True)
    uni_prov = models.CharField(max_length=20, blank=True)
    uni_cant = models.CharField(max_length=30, blank=True)
    uni_parr = models.CharField(max_length=40, blank=True)
    uni_unic = models.CharField(max_length=8, blank=True)
    uni_unid = models.CharField(max_length=40, blank=True)
    uni_tipo = models.CharField(max_length=30, blank=True)
    uni_nive = models.CharField(max_length=8, blank=True)
    eniUser = models.ForeignKey(
        eniUser, null=True, blank=True, on_delete=models.CASCADE, related_name='unidades_salud'
    )


# Crea la tabla de Esquema Regular Temprano
class temprano(models.Model):
    tem_fech = models.DateField()
    tem_intr = models.IntegerField(default=0)
    tem_extr_mies_cnh = models.IntegerField(default=0)
    tem_extr_mies_cibv = models.IntegerField(default=0)
    tem_extr_mine_egen = models.IntegerField(default=0)
    tem_extr_mine_bach = models.IntegerField(default=0)
    tem_extr_visi = models.IntegerField(default=0)
    tem_extr_aten = models.IntegerField(default=0)
    tem_otro = models.IntegerField(default=0)
    tem_sexo_homb = models.IntegerField(default=0)
    tem_sexo_muje = models.IntegerField(default=0)
    tem_luga_pert = models.IntegerField(default=0)
    tem_luga_nope = models.IntegerField(default=0)
    tem_naci_ecua = models.IntegerField(default=0)
    tem_naci_colo = models.IntegerField(default=0)
    tem_naci_peru = models.IntegerField(default=0)
    tem_naci_cuba = models.IntegerField(default=0)
    tem_naci_vene = models.IntegerField(default=0)
    tem_naci_otro = models.IntegerField(default=0)
    tem_auto_indi = models.IntegerField(default=0)
    tem_auto_afro = models.IntegerField(default=0)
    tem_auto_negr = models.IntegerField(default=0)
    tem_auto_mula = models.IntegerField(default=0)
    tem_auto_mont = models.IntegerField(default=0)
    tem_auto_mest = models.IntegerField(default=0)
    tem_auto_blan = models.IntegerField(default=0)
    tem_auto_otro = models.IntegerField(default=0)
    tem_naci_achu = models.IntegerField(default=0)
    tem_naci_ando = models.IntegerField(default=0)
    tem_naci_awa = models.IntegerField(default=0)
    tem_naci_chac = models.IntegerField(default=0)
    tem_naci_cofa = models.IntegerField(default=0)
    tem_naci_eper = models.IntegerField(default=0)
    tem_naci_huan = models.IntegerField(default=0)
    tem_naci_kich = models.IntegerField(default=0)
    tem_naci_mant = models.IntegerField(default=0)
    tem_naci_seco = models.IntegerField(default=0)
    tem_naci_shiw = models.IntegerField(default=0)
    tem_naci_shua = models.IntegerField(default=0)
    tem_naci_sion = models.IntegerField(default=0)
    tem_naci_tsac = models.IntegerField(default=0)
    tem_naci_waor = models.IntegerField(default=0)
    tem_naci_zapa = models.IntegerField(default=0)
    tem_pueb_chib = models.IntegerField(default=0)
    tem_pueb_kana = models.IntegerField(default=0)
    tem_pueb_kara = models.IntegerField(default=0)
    tem_pueb_kaya = models.IntegerField(default=0)
    tem_pueb_kich = models.IntegerField(default=0)
    tem_pueb_kisa = models.IntegerField(default=0)
    tem_pueb_kitu = models.IntegerField(default=0)
    tem_pueb_nata = models.IntegerField(default=0)
    tem_pueb_otav = models.IntegerField(default=0)
    tem_pueb_palt = models.IntegerField(default=0)
    tem_pueb_panz = models.IntegerField(default=0)
    tem_pueb_past = models.IntegerField(default=0)
    tem_pueb_puru = models.IntegerField(default=0)
    tem_pueb_sala = models.IntegerField(default=0)
    tem_pueb_sara = models.IntegerField(default=0)
    tem_pueb_toma = models.IntegerField(default=0)
    tem_pueb_wara = models.IntegerField(default=0)
    tem_men1_dosi_bcgp = models.IntegerField(default=0)
    tem_men1_dosi_hbpr = models.IntegerField(default=0)
    tem_men1_dosi_bcgd = models.IntegerField(default=0)
    tem_men1_1rad_rota = models.IntegerField(default=0)
    tem_men1_1rad_fipv = models.IntegerField(default=0)
    tem_men1_1rad_neum = models.IntegerField(default=0)
    tem_men1_1rad_pent = models.IntegerField(default=0)
    tem_men1_2dad_rota = models.IntegerField(default=0)
    tem_men1_2dad_fipv = models.IntegerField(default=0)
    tem_men1_2dad_neum = models.IntegerField(default=0)
    tem_men1_2dad_pent = models.IntegerField(default=0)
    tem_men1_3rad_bopv = models.IntegerField(default=0)
    tem_men1_3rad_neum = models.IntegerField(default=0)
    tem_men1_3rad_pent = models.IntegerField(default=0)
    tem_12a23m_1rad_srp = models.IntegerField(default=0)
    tem_12a23m_dosi_fa = models.IntegerField(default=0)
    tem_12a23m_dosi_vari = models.IntegerField(default=0)
    tem_12a23m_2dad_srp = models.IntegerField(default=0)
    tem_12a23m_4tad_bopv = models.IntegerField(default=0)
    tem_12a23m_4tad_dpt = models.IntegerField(default=0)
    tem_5ano_5tad_bopv = models.IntegerField(default=0)
    tem_5ano_5tad_dpt = models.IntegerField(default=0)
    tem_9ano_1rad_hpv = models.IntegerField(default=0)
    tem_9ano_2dad_hpv = models.IntegerField(default=0)
    tem_10an_2dad_hpv = models.IntegerField(default=0)
    tem_15an_terc_dtad = models.IntegerField(default=0)
    tem_tota = models.BooleanField(default=False)
    eniUser = models.ForeignKey(
        eniUser, null=True, blank=True, on_delete=models.CASCADE)


# Crea la tabla de Esquema Regular Tardio


class tardio(models.Model):
    tar_fech = models.DateField()
    tar_intr = models.IntegerField(default=0)
    tar_extr_mies_cnh = models.IntegerField(default=0)
    tar_extr_mies_cibv = models.IntegerField(default=0)
    tar_extr_mine_egen = models.IntegerField(default=0)
    tar_extr_mine_bach = models.IntegerField(default=0)
    tar_extr_visi = models.IntegerField(default=0)
    tar_extr_aten = models.IntegerField(default=0)
    tar_otro = models.IntegerField(default=0)
    tar_sexo_homb = models.IntegerField(default=0)
    tar_sexo_muje = models.IntegerField(default=0)
    tar_luga_pert = models.IntegerField(default=0)
    tar_luga_nope = models.IntegerField(default=0)
    tar_naci_ecua = models.IntegerField(default=0)
    tar_naci_colo = models.IntegerField(default=0)
    tar_naci_peru = models.IntegerField(default=0)
    tar_naci_cuba = models.IntegerField(default=0)
    tar_naci_vene = models.IntegerField(default=0)
    tar_naci_otro = models.IntegerField(default=0)
    tar_auto_indi = models.IntegerField(default=0)
    tar_auto_afro = models.IntegerField(default=0)
    tar_auto_negr = models.IntegerField(default=0)
    tar_auto_mula = models.IntegerField(default=0)
    tar_auto_mont = models.IntegerField(default=0)
    tar_auto_mest = models.IntegerField(default=0)
    tar_auto_blan = models.IntegerField(default=0)
    tar_auto_otro = models.IntegerField(default=0)
    tar_naci_achu = models.IntegerField(default=0)
    tar_naci_ando = models.IntegerField(default=0)
    tar_naci_awa = models.IntegerField(default=0)
    tar_naci_chac = models.IntegerField(default=0)
    tar_naci_cofa = models.IntegerField(default=0)
    tar_naci_eper = models.IntegerField(default=0)
    tar_naci_huan = models.IntegerField(default=0)
    tar_naci_kich = models.IntegerField(default=0)
    tar_naci_mant = models.IntegerField(default=0)
    tar_naci_seco = models.IntegerField(default=0)
    tar_naci_shiw = models.IntegerField(default=0)
    tar_naci_shua = models.IntegerField(default=0)
    tar_naci_sion = models.IntegerField(default=0)
    tar_naci_tsac = models.IntegerField(default=0)
    tar_naci_waor = models.IntegerField(default=0)
    tar_naci_zapa = models.IntegerField(default=0)
    tar_pueb_chib = models.IntegerField(default=0)
    tar_pueb_kana = models.IntegerField(default=0)
    tar_pueb_kara = models.IntegerField(default=0)
    tar_pueb_kaya = models.IntegerField(default=0)
    tar_pueb_kich = models.IntegerField(default=0)
    tar_pueb_kisa = models.IntegerField(default=0)
    tar_pueb_kitu = models.IntegerField(default=0)
    tar_pueb_nata = models.IntegerField(default=0)
    tar_pueb_otav = models.IntegerField(default=0)
    tar_pueb_palt = models.IntegerField(default=0)
    tar_pueb_panz = models.IntegerField(default=0)
    tar_pueb_past = models.IntegerField(default=0)
    tar_pueb_puru = models.IntegerField(default=0)
    tar_pueb_sala = models.IntegerField(default=0)
    tar_pueb_sara = models.IntegerField(default=0)
    tar_pueb_toma = models.IntegerField(default=0)
    tar_pueb_wara = models.IntegerField(default=0)
    tar_1ano_1rad_fipv = models.IntegerField(default=0)
    tar_1ano_1rad_hbpe = models.IntegerField(default=0)
    tar_1ano_1rad_dpt = models.IntegerField(default=0)
    tar_1ano_2dad_fipv = models.IntegerField(default=0)
    tar_1ano_2dad_hbpe = models.IntegerField(default=0)
    tar_1ano_2dad_dpt = models.IntegerField(default=0)
    tar_1ano_3rad_bopv = models.IntegerField(default=0)
    tar_1ano_3rad_hbpe = models.IntegerField(default=0)
    tar_1ano_3rad_dpt = models.IntegerField(default=0)
    tar_2ano_1rad_fipv = models.IntegerField(default=0)
    tar_2ano_1rad_srp = models.IntegerField(default=0)
    tar_2ano_1rad_hbpe = models.IntegerField(default=0)
    tar_2ano_1rad_dpt = models.IntegerField(default=0)
    tar_2ano_2dad_fipv = models.IntegerField(default=0)
    tar_2ano_2dad_srp = models.IntegerField(default=0)
    tar_2ano_2dad_hbpe = models.IntegerField(default=0)
    tar_2ano_2dad_dpt = models.IntegerField(default=0)
    tar_2ano_3rad_bopv = models.IntegerField(default=0)
    tar_2ano_3rad_hbpe = models.IntegerField(default=0)
    tar_2ano_3rad_dpt = models.IntegerField(default=0)
    tar_2ano_4tad_bopv = models.IntegerField(default=0)
    tar_2ano_4tad_dpt = models.IntegerField(default=0)
    tar_2ano_dosi_fa = models.IntegerField(default=0)
    tar_3ano_1rad_fipv = models.IntegerField(default=0)
    tar_3ano_1rad_srp = models.IntegerField(default=0)
    tar_3ano_1rad_hbpe = models.IntegerField(default=0)
    tar_3ano_1rad_dpt = models.IntegerField(default=0)
    tar_3ano_2dad_fipv = models.IntegerField(default=0)
    tar_3ano_2dad_srp = models.IntegerField(default=0)
    tar_3ano_2dad_hbpe = models.IntegerField(default=0)
    tar_3ano_2dad_dpt = models.IntegerField(default=0)
    tar_3ano_3rad_bopv = models.IntegerField(default=0)
    tar_3ano_3rad_hbpe = models.IntegerField(default=0)
    tar_3ano_3rad_dpt = models.IntegerField(default=0)
    tar_3ano_4tad_bopv = models.IntegerField(default=0)
    tar_3ano_4tad_dpt = models.IntegerField(default=0)
    tar_3ano_dosi_fa = models.IntegerField(default=0)
    tar_4ano_1rad_fipv = models.IntegerField(default=0)
    tar_4ano_1rad_srp = models.IntegerField(default=0)
    tar_4ano_1rad_hbpe = models.IntegerField(default=0)
    tar_4ano_1rad_dpt = models.IntegerField(default=0)
    tar_4ano_2dad_fipv = models.IntegerField(default=0)
    tar_4ano_2dad_srp = models.IntegerField(default=0)
    tar_4ano_2dad_hbpe = models.IntegerField(default=0)
    tar_4ano_2dad_dpt = models.IntegerField(default=0)
    tar_4ano_3rad_bopv = models.IntegerField(default=0)
    tar_4ano_3rad_hbpe = models.IntegerField(default=0)
    tar_4ano_3rad_dpt = models.IntegerField(default=0)
    tar_4ano_4tad_bopv = models.IntegerField(default=0)
    tar_4ano_4tad_dpt = models.IntegerField(default=0)
    tar_4ano_dosi_fa = models.IntegerField(default=0)
    tar_5ano_1rad_ipv = models.IntegerField(default=0)
    tar_5ano_1rad_srp = models.IntegerField(default=0)
    tar_5ano_1rad_hbpe = models.IntegerField(default=0)
    tar_5ano_1rad_dpt = models.IntegerField(default=0)
    tar_5ano_2dad_fipv = models.IntegerField(default=0)
    tar_5ano_2dad_srp = models.IntegerField(default=0)
    tar_5ano_2dad_hbpe = models.IntegerField(default=0)
    tar_5ano_2dad_dpt = models.IntegerField(default=0)
    tar_5ano_3rad_bopv = models.IntegerField(default=0)
    tar_5ano_3rad_hbpe = models.IntegerField(default=0)
    tar_5ano_3rad_dpt = models.IntegerField(default=0)
    tar_5ano_4tad_bopv = models.IntegerField(default=0)
    tar_5ano_4tad_dpt = models.IntegerField(default=0)
    tar_5ano_dosi_fa = models.IntegerField(default=0)
    tar_6ano_1rad_srp = models.IntegerField(default=0)
    tar_6ano_2dad_srp = models.IntegerField(default=0)
    tar_6ano_dosi_fa = models.IntegerField(default=0)
    tar_7ano_1rad_sr = models.IntegerField(default=0)
    tar_7ano_2dad_sr = models.IntegerField(default=0)
    tar_7ano_dosi_fa = models.IntegerField(default=0)
    tar_8ano_dosi_fa = models.IntegerField(default=0)
    tar_7a14_dosi_dtad = models.IntegerField(default=0)
    tar_9a14_dosi_fa = models.IntegerField(default=0)
    tar_15a19_dosi_fa = models.IntegerField(default=0)
    tar_20a59_dosi_fa = models.IntegerField(default=0)
    tar_8a14_1rad_sr = models.IntegerField(default=0)
    tar_8a14_2dad_sr = models.IntegerField(default=0)
    tar_15a29_1rad_sr = models.IntegerField(default=0)
    tar_15a29_2dad_sr = models.IntegerField(default=0)
    tar_30a50_1rad_sr = models.IntegerField(default=0)
    tar_30a50_2dad_sr = models.IntegerField(default=0)
    tar_16a49mefne_dtad_prim = models.IntegerField(default=0)
    tar_16a49mefne_dtad_segu = models.IntegerField(default=0)
    tar_16a49mefne_dtad_terc = models.IntegerField(default=0)
    tar_16a49mefne_dtad_cuar = models.IntegerField(default=0)
    tar_16a49mefne_dtad_quin = models.IntegerField(default=0)
    tar_mefe_dtad_prim = models.IntegerField(default=0)
    tar_mefe_dtad_segu = models.IntegerField(default=0)
    tar_mefe_dtad_terc = models.IntegerField(default=0)
    tar_mefe_dtad_cuar = models.IntegerField(default=0)
    tar_mefe_dtad_quin = models.IntegerField(default=0)
    tar_16a49_dtad_prim = models.IntegerField(default=0)
    tar_16a49_dtad_segu = models.IntegerField(default=0)
    tar_16a49_dtad_terc = models.IntegerField(default=0)
    tar_16a49_dtad_cuar = models.IntegerField(default=0)
    tar_16a49_dtad_quin = models.IntegerField(default=0)
    tar_hepa_trasal_prim = models.IntegerField(default=0)
    tar_hepa_trasal_segu = models.IntegerField(default=0)
    tar_hepa_trasal_terc = models.IntegerField(default=0)
    tar_hepa_estsal_prim = models.IntegerField(default=0)
    tar_hepa_estsal_segu = models.IntegerField(default=0)
    tar_hepa_estsal_terc = models.IntegerField(default=0)
    tar_hepa_trasex_prim = models.IntegerField(default=0)
    tar_hepa_trasex_segu = models.IntegerField(default=0)
    tar_hepa_trasex_terc = models.IntegerField(default=0)
    tar_hepa_pervih_prim = models.IntegerField(default=0)
    tar_hepa_pervih_segu = models.IntegerField(default=0)
    tar_hepa_pervih_terc = models.IntegerField(default=0)
    tar_hepa_perppl_prim = models.IntegerField(default=0)
    tar_hepa_perppl_segu = models.IntegerField(default=0)
    tar_hepa_perppl_terc = models.IntegerField(default=0)
    tar_hepa_otro_prim = models.IntegerField(default=0)
    tar_hepa_otro_segu = models.IntegerField(default=0)
    tar_hepa_otro_terc = models.IntegerField(default=0)
    tar_inmant = models.IntegerField(default=0)
    tar_inmanthep = models.IntegerField(default=0)
    tar_inmantrra = models.IntegerField(default=0)
    tar_tota = models.BooleanField(default=False)
    eniUser = models.ForeignKey(
        eniUser, null=True, blank=True, on_delete=models.CASCADE)

    '''@classmethod
    def get_by_month_and_user(cls, user_id, month, year):
        return cls.objects.filter(
            eniUser_id=user_id,
            tar_fech__year=year,
            tar_fech__month=month
        ).order_by('tar_fech')'''

# Crea la tabla de Esquema Regular Desperdicio


class desperdicio(models.Model):
    des_fech = models.DateField()
    des_bcg_dosapli = models.IntegerField(default=0)
    des_bcg_pervacenfabi = models.IntegerField(default=0)
    des_bcg_pervacfrasnoabi = models.IntegerField(default=0)
    des_hbpe_dosapli = models.IntegerField(default=0)
    des_hbpe_pervacenfabi = models.IntegerField(default=0)
    des_hbpe_pervacfrasnoabi = models.IntegerField(default=0)
    des_rota_dosapli = models.IntegerField(default=0)
    des_rota_pervacenfabi = models.IntegerField(default=0)
    des_rota_pervacfrasnoabi = models.IntegerField(default=0)
    des_pent_dosapli = models.IntegerField(default=0)
    des_pent_pervacenfabi = models.IntegerField(default=0)
    des_pent_pervacfrasnoabi = models.IntegerField(default=0)
    des_fipv_dosapli = models.IntegerField(default=0)
    des_fipv_pervacenfabi = models.IntegerField(default=0)
    des_fipv_pervacfrasnoabi = models.IntegerField(default=0)
    des_anti_dosapli = models.IntegerField(default=0)
    des_anti_pervacenfabi = models.IntegerField(default=0)
    des_anti_pervacfrasnoabi = models.IntegerField(default=0)
    des_neum_dosapli = models.IntegerField(default=0)
    des_neum_pervacenfabi = models.IntegerField(default=0)
    des_neum_pervacfrasnoabi = models.IntegerField(default=0)
    des_sr_dosapli = models.IntegerField(default=0)
    des_sr_pervacenfabi = models.IntegerField(default=0)
    des_sr_pervacfrasnoabi = models.IntegerField(default=0)
    des_srp_dosapli = models.IntegerField(default=0)
    des_srp_pervacenfabi = models.IntegerField(default=0)
    des_srp_pervacfrasnoabi = models.IntegerField(default=0)
    des_vari_dosapli = models.IntegerField(default=0)
    des_vari_pervacenfabi = models.IntegerField(default=0)
    des_vari_pervacfrasnoabi = models.IntegerField(default=0)
    des_fieb_dosapli = models.IntegerField(default=0)
    des_fieb_pervacenfabi = models.IntegerField(default=0)
    des_fieb_pervacfrasnoabi = models.IntegerField(default=0)
    des_dift_dosapli = models.IntegerField(default=0)
    des_dift_pervacenfabi = models.IntegerField(default=0)
    des_dift_pervacfrasnoabi = models.IntegerField(default=0)
    des_hpv_dosapli = models.IntegerField(default=0)
    des_hpv_pervacenfabi = models.IntegerField(default=0)
    des_hpv_pervacfrasnoabi = models.IntegerField(default=0)
    des_dtad_dosapli = models.IntegerField(default=0)
    des_dtad_pervacenfabi = models.IntegerField(default=0)
    des_dtad_pervacfrasnoabi = models.IntegerField(default=0)
    des_hepa_dosapli = models.IntegerField(default=0)
    des_hepa_pervacenfabi = models.IntegerField(default=0)
    des_hepa_pervacfrasnoabi = models.IntegerField(default=0)
    des_inmant_dosapli = models.IntegerField(default=0)
    des_inmant_pervacenfabi = models.IntegerField(default=0)
    des_inmant_pervacfrasnoabi = models.IntegerField(default=0)
    des_inmanthepb_dosapli = models.IntegerField(default=0)
    des_inmanthepb_pervacenfabi = models.IntegerField(default=0)
    des_inmanthepb_pervacfrasnoabi = models.IntegerField(default=0)
    des_inmantrra_dosapli = models.IntegerField(default=0)
    des_inmantrra_pervacenfabi = models.IntegerField(default=0)
    des_inmantrra_pervacfrasnoabi = models.IntegerField(default=0)
    des_infped_dosapli = models.IntegerField(default=0)
    des_infped_pervacenfabi = models.IntegerField(default=0)
    des_infped_pervacfrasnoabi = models.IntegerField(default=0)
    des_infadu_dosapli = models.IntegerField(default=0)
    des_infadu_pervacenfabi = models.IntegerField(default=0)
    des_infadu_pervacfrasnoabi = models.IntegerField(default=0)
    des_viru_dosapli = models.IntegerField(default=0)
    des_viru_pervacenfabi = models.IntegerField(default=0)
    des_viru_pervacfrasnoabi = models.IntegerField(default=0)
    des_vacsin_dosapli = models.IntegerField(default=0)
    des_vacsin_pervacenfabi = models.IntegerField(default=0)
    des_vacsin_pervacfrasnoabi = models.IntegerField(default=0)
    des_vacpfi_dosapli = models.IntegerField(default=0)
    des_vacpfi_pervacenfabi = models.IntegerField(default=0)
    des_vacpfi_pervacfrasnoabi = models.IntegerField(default=0)
    des_vacmod_dosapli = models.IntegerField(default=0)
    des_vacmod_pervacenfabi = models.IntegerField(default=0)
    des_vacmod_pervacfrasnoabi = models.IntegerField(default=0)
    des_vacvphcam_dosapli = models.IntegerField(default=0)
    des_vacvphcam_pervacenfabi = models.IntegerField(default=0)
    des_vacvphcam_pervacfrasnoabi = models.IntegerField(default=0)
    des_tota = models.BooleanField(default=False)
    eniUser = models.ForeignKey(
        'eniUser', null=True, blank=True, on_delete=models.CASCADE)

# Crea la tabla de Campaña de Vacunación Registro Paciente


class admision_datos(models.Model):
    adm_dato_fech = models.DateField(auto_now_add=True)
    adm_dato_fech_actu = models.DateField(auto_now=True)
    adm_dato_pers_tipo_iden = models.CharField(max_length=30, blank=True)
    adm_dato_pers_nume_iden = models.CharField(
        max_length=20, blank=True, unique=True)
    adm_dato_pers_apel = models.CharField(max_length=40, blank=True)
    adm_dato_pers_nomb = models.CharField(max_length=40, blank=True)
    adm_dato_pers_esta_civi = models.CharField(max_length=20, blank=True)
    adm_dato_pers_sexo = models.CharField(max_length=15, blank=True)
    adm_dato_pers_tele = models.CharField(max_length=15, blank=True)
    adm_dato_pers_celu = models.CharField(max_length=15, blank=True)
    adm_dato_pers_corr_elec = models.EmailField(max_length=40, blank=True)
    adm_dato_naci_naci = models.CharField(max_length=30, blank=True)
    adm_dato_naci_luga_naci = models.CharField(max_length=40, blank=True)
    adm_dato_naci_prov = models.CharField(max_length=30, blank=True)
    adm_dato_naci_cant = models.CharField(max_length=30, blank=True)
    adm_dato_naci_parr = models.CharField(max_length=40, blank=True)
    adm_dato_naci_fech_naci = models.DateField(blank=True, null=True)
    adm_dato_resi_pais_resi = models.CharField(max_length=30, blank=True)
    adm_dato_resi_prov = models.CharField(max_length=20, blank=True)
    adm_dato_resi_cant = models.CharField(max_length=30, blank=True)
    adm_dato_resi_parr = models.CharField(max_length=40, blank=True)
    adm_dato_resi_call_prin = models.CharField(max_length=40, blank=True)
    adm_dato_resi_nume = models.CharField(max_length=10, blank=True)
    adm_dato_resi_call_secu = models.CharField(max_length=30, blank=True)
    adm_dato_resi_barr = models.CharField(max_length=40, blank=True)
    adm_dato_resi_refe_resi = models.CharField(max_length=40, blank=True)
    adm_dato_adic_auto_etni = models.CharField(max_length=30, blank=True)
    adm_dato_adic_naci_etni = models.CharField(max_length=30, blank=True)
    adm_dato_adic_pueb_kich = models.CharField(max_length=30, blank=True)
    adm_dato_adic_nive_educ = models.CharField(max_length=30, blank=True)
    adm_dato_adic_esta_nive_educ = models.CharField(max_length=30, blank=True)
    adm_dato_adic_tipo_empr_trab = models.CharField(max_length=30, blank=True)
    adm_dato_adic_ocup_prin = models.CharField(max_length=30, blank=True)
    adm_dato_adic_segu_salu_prin = models.CharField(max_length=30, blank=True)
    adm_dato_adic_segu_salu_secu = models.CharField(max_length=30, blank=True)
    adm_dato_adic_tipo_bono_reci = models.CharField(max_length=30, blank=True)
    adm_dato_adic_tien_disc = models.CharField(max_length=30, blank=True)
    adm_dato_repr_tipo_iden = models.CharField(max_length=30, blank=True)
    adm_dato_repr_nume_iden = models.CharField(max_length=20, blank=True)
    adm_dato_repr_naci = models.CharField(max_length=30, blank=True)
    adm_dato_repr_apel = models.CharField(max_length=40, blank=True)
    adm_dato_repr_nomb = models.CharField(max_length=40, blank=True)
    adm_dato_repr_reci_bono = models.CharField(max_length=30, blank=True)
    adm_dato_repr_pare = models.CharField(max_length=30, blank=True)
    adm_dato_repr_nume_tele = models.CharField(max_length=15, blank=True)
    adm_dato_cont_enca_nece_llam = models.CharField(max_length=30, blank=True)
    adm_dato_cont_pare = models.CharField(max_length=30, blank=True)
    adm_dato_cont_tele = models.CharField(max_length=15, blank=True)
    adm_dato_cont_dire = models.CharField(max_length=40, blank=True)


class registro_vacunado(models.Model):
    vac_reg_ano_mes_dia_apli = models.DateField()
    vac_reg_punt_vacu = models.CharField(max_length=40, blank=True)
    vac_reg_unic_esta = models.CharField(max_length=8, blank=True)
    vac_reg_nomb_esta_salu = models.CharField(max_length=40, blank=True)
    vac_reg_zona = models.CharField(max_length=8, blank=True)
    vac_reg_dist = models.CharField(max_length=8, blank=True)
    vac_reg_prov = models.CharField(max_length=20, blank=True)
    vac_reg_cant = models.CharField(max_length=30, blank=True)
    vac_reg_apel = models.CharField(max_length=40, blank=True)
    vac_reg_nomb = models.CharField(max_length=40, blank=True)
    vac_reg_tipo_iden = models.CharField(max_length=30, blank=True)
    vac_reg_nume_iden = models.CharField(max_length=20, blank=True)
    vac_reg_sexo = models.CharField(max_length=10, blank=True)
    vac_reg_ano_mes_dia_naci = models.DateField()
    vac_reg_naci = models.CharField(max_length=30, blank=True)
    vac_reg_etni = models.CharField(max_length=20, blank=True)
    vac_reg_naci_etni = models.CharField(max_length=30, blank=True)
    vac_reg_pueb = models.CharField(max_length=30, blank=True)
    vac_reg_resi_prov = models.CharField(max_length=20, blank=True)
    vac_reg_resi_cant = models.CharField(max_length=30, blank=True)
    vac_reg_resi_parr = models.CharField(max_length=40, blank=True)
    vac_reg_teld_cont = models.CharField(max_length=15, blank=True)
    vac_reg_corr_elec = models.CharField(max_length=40, blank=True)
    vac_reg_grup_ries = models.CharField(max_length=40, blank=True)
    vac_reg_fase_vacu = models.IntegerField(default=0)
    vac_reg_esta_vacu = models.CharField(max_length=15, blank=True)
    vac_reg_tipo_esqu = models.CharField(max_length=30, blank=True)
    vac_reg_vacu = models.CharField(max_length=40, blank=True)
    vac_reg_lote_vacu = models.CharField(max_length=20, blank=True)
    vac_reg_dosi_apli = models.IntegerField(default=0)
    vac_reg_paci_agen = models.CharField(max_length=8, blank=True)
    vac_reg_nomb_vacu = models.CharField(max_length=40, blank=True)
    vac_reg_iden_vacu = models.CharField(max_length=20, blank=True)
    vac_reg_nomb_prof_regi = models.CharField(max_length=40, blank=True)
    vac_reg_reci_dosi_prev_exte = models.CharField(max_length=8, blank=True)
    vac_reg_nomb_dosi_exte = models.CharField(max_length=40, blank=True)
    vac_reg_fech_anio_mes_dia_dosi_exte = models.DateField()
    vac_reg_pais_dosi_exte = models.CharField(max_length=30, blank=True)
    vac_reg_lote_dosi_exte = models.CharField(max_length=20, blank=True)
    eniUser = models.ForeignKey(
        'eniUser', null=True, blank=True, on_delete=models.CASCADE)
