from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager


class EniUserManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        """
        Create and return a regular user with a username and password.
        """
        if not username:
            raise ValueError('The Username field must be set')
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        """
        Create and return a superuser with a username and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(username, password, **extra_fields)

# Create your models here.


class eniUser(AbstractUser):
    username = models.CharField(max_length=20, unique=True)
    email = models.EmailField(max_length=40, blank=True)
    fun_tipo_iden = models.CharField(max_length=30, blank=True)
    fun_sex = models.CharField(max_length=10, blank=True)
    fun_titu = models.CharField(max_length=40, blank=True)
    fun_esta = models.IntegerField(default=0)
    fun_admi_rol = models.IntegerField(default=0)
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    objects = EniUserManager()

    @classmethod
    def get_all_users(cls):
        return cls.objects.all()

    # def nombre_completo(self):
    #     return self.first_name + " " + self.last_name

    # def __str__(self) -> str:
    #     return self.nombre_completo()


# Crea la tabla de Unidad de Salud
class unidad_salud(models.Model):
    uni_inst_sist = models.CharField(max_length=15, blank=True)
    uni_zona = models.CharField(max_length=10, blank=True)
    uni_dist = models.CharField(max_length=8, blank=True)
    uni_prov = models.CharField(max_length=20, blank=True)
    uni_cant = models.CharField(max_length=30, blank=True)
    uni_parr = models.CharField(max_length=40, blank=True)
    uni_unic = models.CharField(max_length=8, blank=True)
    uni_unid = models.CharField(max_length=40, blank=True)
    uni_tipo = models.CharField(max_length=30, blank=True)
    uni_nive = models.CharField(max_length=8, blank=True)
    eniUser = models.ForeignKey(
        eniUser, null=True, blank=True, on_delete=models.CASCADE, related_name='unidades_salud'
    )


# Crea la tabla de Esquema Regular Temprano
class temprano(models.Model):
    tem_fech = models.DateField()
    tem_intr = models.IntegerField(default=0)
    tem_extr_mies_cnh = models.IntegerField(default=0)
    tem_extr_mies_cibv = models.IntegerField(default=0)
    tem_extr_mine_egen = models.IntegerField(default=0)
    tem_extr_mine_bach = models.IntegerField(default=0)
    tem_extr_visi = models.IntegerField(default=0)
    tem_extr_aten = models.IntegerField(default=0)
    tem_otro = models.IntegerField(default=0)
    tem_sexo_homb = models.IntegerField(default=0)
    tem_sexo_muje = models.IntegerField(default=0)
    tem_luga_pert = models.IntegerField(default=0)
    tem_luga_nope = models.IntegerField(default=0)
    tem_naci_ecua = models.IntegerField(default=0)
    tem_naci_colo = models.IntegerField(default=0)
    tem_naci_peru = models.IntegerField(default=0)
    tem_naci_cuba = models.IntegerField(default=0)
    tem_naci_vene = models.IntegerField(default=0)
    tem_naci_otro = models.IntegerField(default=0)
    tem_auto_indi = models.IntegerField(default=0)
    tem_auto_afro = models.IntegerField(default=0)
    tem_auto_negr = models.IntegerField(default=0)
    tem_auto_mula = models.IntegerField(default=0)
    tem_auto_mont = models.IntegerField(default=0)
    tem_auto_mest = models.IntegerField(default=0)
    tem_auto_blan = models.IntegerField(default=0)
    tem_auto_otro = models.IntegerField(default=0)
    tem_naci_achu = models.IntegerField(default=0)
    tem_naci_ando = models.IntegerField(default=0)
    tem_naci_awa = models.IntegerField(default=0)
    tem_naci_chac = models.IntegerField(default=0)
    tem_naci_cofa = models.IntegerField(default=0)
    tem_naci_eper = models.IntegerField(default=0)
    tem_naci_huan = models.IntegerField(default=0)
    tem_naci_kich = models.IntegerField(default=0)
    tem_naci_mant = models.IntegerField(default=0)
    tem_naci_seco = models.IntegerField(default=0)
    tem_naci_shiw = models.IntegerField(default=0)
    tem_naci_shua = models.IntegerField(default=0)
    tem_naci_sion = models.IntegerField(default=0)
    tem_naci_tsac = models.IntegerField(default=0)
    tem_naci_waor = models.IntegerField(default=0)
    tem_naci_zapa = models.IntegerField(default=0)
    tem_pueb_chib = models.IntegerField(default=0)
    tem_pueb_kana = models.IntegerField(default=0)
    tem_pueb_kara = models.IntegerField(default=0)
    tem_pueb_kaya = models.IntegerField(default=0)
    tem_pueb_kich = models.IntegerField(default=0)
    tem_pueb_kisa = models.IntegerField(default=0)
    tem_pueb_kitu = models.IntegerField(default=0)
    tem_pueb_nata = models.IntegerField(default=0)
    tem_pueb_otav = models.IntegerField(default=0)
    tem_pueb_palt = models.IntegerField(default=0)
    tem_pueb_panz = models.IntegerField(default=0)
    tem_pueb_past = models.IntegerField(default=0)
    tem_pueb_puru = models.IntegerField(default=0)
    tem_pueb_sala = models.IntegerField(default=0)
    tem_pueb_sara = models.IntegerField(default=0)
    tem_pueb_toma = models.IntegerField(default=0)
    tem_pueb_wara = models.IntegerField(default=0)
    tem_men1_dosi_bcgp = models.IntegerField(default=0)
    tem_men1_dosi_hbpr = models.IntegerField(default=0)
    tem_men1_dosi_bcgd = models.IntegerField(default=0)
    tem_men1_1rad_rota = models.IntegerField(default=0)
    tem_men1_1rad_fipv = models.IntegerField(default=0)
    tem_men1_1rad_neum = models.IntegerField(default=0)
    tem_men1_1rad_pent = models.IntegerField(default=0)
    tem_men1_2dad_rota = models.IntegerField(default=0)
    tem_men1_2dad_fipv = models.IntegerField(default=0)
    tem_men1_2dad_neum = models.IntegerField(default=0)
    tem_men1_2dad_pent = models.IntegerField(default=0)
    tem_men1_3rad_bopv = models.IntegerField(default=0)
    tem_men1_3rad_neum = models.IntegerField(default=0)
    tem_men1_3rad_pent = models.IntegerField(default=0)
    tem_12a23m_1rad_srp = models.IntegerField(default=0)
    tem_12a23m_dosi_fa = models.IntegerField(default=0)
    tem_12a23m_dosi_vari = models.IntegerField(default=0)
    tem_12a23m_2dad_srp = models.IntegerField(default=0)
    tem_12a23m_4tad_bopv = models.IntegerField(default=0)
    tem_12a23m_4tad_dpt = models.IntegerField(default=0)
    tem_5ano_5tad_bopv = models.IntegerField(default=0)
    tem_5ano_5tad_dpt = models.IntegerField(default=0)
    tem_9ano_1rad_hpv = models.IntegerField(default=0)
    tem_9ano_2dad_hpv = models.IntegerField(default=0)
    tem_10an_2dad_hpv = models.IntegerField(default=0)
    tem_15an_terc_dtad = models.IntegerField(default=0)
    tem_tota = models.BooleanField(default=False)
    eniUser = models.ForeignKey(
        eniUser, null=True, blank=True, on_delete=models.CASCADE)


# Crea la tabla de Esquema Regular Tardio


class tardio(models.Model):
    tar_fech = models.DateField()
    tar_intr = models.IntegerField(default=0)
    tar_extr_mies_cnh = models.IntegerField(default=0)
    tar_extr_mies_cibv = models.IntegerField(default=0)
    tar_extr_mine_egen = models.IntegerField(default=0)
    tar_extr_mine_bach = models.IntegerField(default=0)
    tar_extr_visi = models.IntegerField(default=0)
    tar_extr_aten = models.IntegerField(default=0)
    tar_otro = models.IntegerField(default=0)
    tar_sexo_homb = models.IntegerField(default=0)
    tar_sexo_muje = models.IntegerField(default=0)
    tar_luga_pert = models.IntegerField(default=0)
    tar_luga_nope = models.IntegerField(default=0)
    tar_naci_ecua = models.IntegerField(default=0)
    tar_naci_colo = models.IntegerField(default=0)
    tar_naci_peru = models.IntegerField(default=0)
    tar_naci_cuba = models.IntegerField(default=0)
    tar_naci_vene = models.IntegerField(default=0)
    tar_naci_otro = models.IntegerField(default=0)
    tar_auto_indi = models.IntegerField(default=0)
    tar_auto_afro = models.IntegerField(default=0)
    tar_auto_negr = models.IntegerField(default=0)
    tar_auto_mula = models.IntegerField(default=0)
    tar_auto_mont = models.IntegerField(default=0)
    tar_auto_mest = models.IntegerField(default=0)
    tar_auto_blan = models.IntegerField(default=0)
    tar_auto_otro = models.IntegerField(default=0)
    tar_naci_achu = models.IntegerField(default=0)
    tar_naci_ando = models.IntegerField(default=0)
    tar_naci_awa = models.IntegerField(default=0)
    tar_naci_chac = models.IntegerField(default=0)
    tar_naci_cofa = models.IntegerField(default=0)
    tar_naci_eper = models.IntegerField(default=0)
    tar_naci_huan = models.IntegerField(default=0)
    tar_naci_kich = models.IntegerField(default=0)
    tar_naci_mant = models.IntegerField(default=0)
    tar_naci_seco = models.IntegerField(default=0)
    tar_naci_shiw = models.IntegerField(default=0)
    tar_naci_shua = models.IntegerField(default=0)
    tar_naci_sion = models.IntegerField(default=0)
    tar_naci_tsac = models.IntegerField(default=0)
    tar_naci_waor = models.IntegerField(default=0)
    tar_naci_zapa = models.IntegerField(default=0)
    tar_pueb_chib = models.IntegerField(default=0)
    tar_pueb_kana = models.IntegerField(default=0)
    tar_pueb_kara = models.IntegerField(default=0)
    tar_pueb_kaya = models.IntegerField(default=0)
    tar_pueb_kich = models.IntegerField(default=0)
    tar_pueb_kisa = models.IntegerField(default=0)
    tar_pueb_kitu = models.IntegerField(default=0)
    tar_pueb_nata = models.IntegerField(default=0)
    tar_pueb_otav = models.IntegerField(default=0)
    tar_pueb_palt = models.IntegerField(default=0)
    tar_pueb_panz = models.IntegerField(default=0)
    tar_pueb_past = models.IntegerField(default=0)
    tar_pueb_puru = models.IntegerField(default=0)
    tar_pueb_sala = models.IntegerField(default=0)
    tar_pueb_sara = models.IntegerField(default=0)
    tar_pueb_toma = models.IntegerField(default=0)
    tar_pueb_wara = models.IntegerField(default=0)
    tar_1ano_1rad_fipv = models.IntegerField(default=0)
    tar_1ano_1rad_hbpe = models.IntegerField(default=0)
    tar_1ano_1rad_dpt = models.IntegerField(default=0)
    tar_1ano_2dad_fipv = models.IntegerField(default=0)
    tar_1ano_2dad_hbpe = models.IntegerField(default=0)
    tar_1ano_2dad_dpt = models.IntegerField(default=0)
    tar_1ano_3rad_bopv = models.IntegerField(default=0)
    tar_1ano_3rad_hbpe = models.IntegerField(default=0)
    tar_1ano_3rad_dpt = models.IntegerField(default=0)
    tar_2ano_1rad_fipv = models.IntegerField(default=0)
    tar_2ano_1rad_srp = models.IntegerField(default=0)
    tar_2ano_1rad_hbpe = models.IntegerField(default=0)
    tar_2ano_1rad_dpt = models.IntegerField(default=0)
    tar_2ano_2dad_fipv = models.IntegerField(default=0)
    tar_2ano_2dad_srp = models.IntegerField(default=0)
    tar_2ano_2dad_hbpe = models.IntegerField(default=0)
    tar_2ano_2dad_dpt = models.IntegerField(default=0)
    tar_2ano_3rad_bopv = models.IntegerField(default=0)
    tar_2ano_3rad_hbpe = models.IntegerField(default=0)
    tar_2ano_3rad_dpt = models.IntegerField(default=0)
    tar_2ano_4tad_bopv = models.IntegerField(default=0)
    tar_2ano_4tad_dpt = models.IntegerField(default=0)
    tar_2ano_dosi_fa = models.IntegerField(default=0)
    tar_3ano_1rad_fipv = models.IntegerField(default=0)
    tar_3ano_1rad_srp = models.IntegerField(default=0)
    tar_3ano_1rad_hbpe = models.IntegerField(default=0)
    tar_3ano_1rad_dpt = models.IntegerField(default=0)
    tar_3ano_2dad_fipv = models.IntegerField(default=0)
    tar_3ano_2dad_srp = models.IntegerField(default=0)
    tar_3ano_2dad_hbpe = models.IntegerField(default=0)
    tar_3ano_2dad_dpt = models.IntegerField(default=0)
    tar_3ano_3rad_bopv = models.IntegerField(default=0)
    tar_3ano_3rad_hbpe = models.IntegerField(default=0)
    tar_3ano_3rad_dpt = models.IntegerField(default=0)
    tar_3ano_4tad_bopv = models.IntegerField(default=0)
    tar_3ano_4tad_dpt = models.IntegerField(default=0)
    tar_3ano_dosi_fa = models.IntegerField(default=0)
    tar_4ano_1rad_fipv = models.IntegerField(default=0)
    tar_4ano_1rad_srp = models.IntegerField(default=0)
    tar_4ano_1rad_hbpe = models.IntegerField(default=0)
    tar_4ano_1rad_dpt = models.IntegerField(default=0)
    tar_4ano_2dad_fipv = models.IntegerField(default=0)
    tar_4ano_2dad_srp = models.IntegerField(default=0)
    tar_4ano_2dad_hbpe = models.IntegerField(default=0)
    tar_4ano_2dad_dpt = models.IntegerField(default=0)
    tar_4ano_3rad_bopv = models.IntegerField(default=0)
    tar_4ano_3rad_hbpe = models.IntegerField(default=0)
    tar_4ano_3rad_dpt = models.IntegerField(default=0)
    tar_4ano_4tad_bopv = models.IntegerField(default=0)
    tar_4ano_4tad_dpt = models.IntegerField(default=0)
    tar_4ano_dosi_fa = models.IntegerField(default=0)
    tar_5ano_1rad_ipv = models.IntegerField(default=0)
    tar_5ano_1rad_srp = models.IntegerField(default=0)
    tar_5ano_1rad_hbpe = models.IntegerField(default=0)
    tar_5ano_1rad_dpt = models.IntegerField(default=0)
    tar_5ano_2dad_fipv = models.IntegerField(default=0)
    tar_5ano_2dad_srp = models.IntegerField(default=0)
    tar_5ano_2dad_hbpe = models.IntegerField(default=0)
    tar_5ano_2dad_dpt = models.IntegerField(default=0)
    tar_5ano_3rad_bopv = models.IntegerField(default=0)
    tar_5ano_3rad_hbpe = models.IntegerField(default=0)
    tar_5ano_3rad_dpt = models.IntegerField(default=0)
    tar_5ano_4tad_bopv = models.IntegerField(default=0)
    tar_5ano_4tad_dpt = models.IntegerField(default=0)
    tar_5ano_dosi_fa = models.IntegerField(default=0)
    tar_6ano_1rad_srp = models.IntegerField(default=0)
    tar_6ano_2dad_srp = models.IntegerField(default=0)
    tar_6ano_dosi_fa = models.IntegerField(default=0)
    tar_7ano_1rad_sr = models.IntegerField(default=0)
    tar_7ano_2dad_sr = models.IntegerField(default=0)
    tar_7ano_dosi_fa = models.IntegerField(default=0)
    tar_8ano_dosi_fa = models.IntegerField(default=0)
    tar_7a14_dosi_dtad = models.IntegerField(default=0)
    tar_9a14_dosi_fa = models.IntegerField(default=0)
    tar_15a19_dosi_fa = models.IntegerField(default=0)
    tar_20a59_dosi_fa = models.IntegerField(default=0)
    tar_8a14_1rad_sr = models.IntegerField(default=0)
    tar_8a14_2dad_sr = models.IntegerField(default=0)
    tar_15a29_1rad_sr = models.IntegerField(default=0)
    tar_15a29_2dad_sr = models.IntegerField(default=0)
    tar_30a50_1rad_sr = models.IntegerField(default=0)
    tar_30a50_2dad_sr = models.IntegerField(default=0)
    tar_16a49mefne_dtad_prim = models.IntegerField(default=0)
    tar_16a49mefne_dtad_segu = models.IntegerField(default=0)
    tar_16a49mefne_dtad_terc = models.IntegerField(default=0)
    tar_16a49mefne_dtad_cuar = models.IntegerField(default=0)
    tar_16a49mefne_dtad_quin = models.IntegerField(default=0)
    tar_mefe_dtad_prim = models.IntegerField(default=0)
    tar_mefe_dtad_segu = models.IntegerField(default=0)
    tar_mefe_dtad_terc = models.IntegerField(default=0)
    tar_mefe_dtad_cuar = models.IntegerField(default=0)
    tar_mefe_dtad_quin = models.IntegerField(default=0)
    tar_16a49_dtad_prim = models.IntegerField(default=0)
    tar_16a49_dtad_segu = models.IntegerField(default=0)
    tar_16a49_dtad_terc = models.IntegerField(default=0)
    tar_16a49_dtad_cuar = models.IntegerField(default=0)
    tar_16a49_dtad_quin = models.IntegerField(default=0)
    tar_hepa_trasal_prim = models.IntegerField(default=0)
    tar_hepa_trasal_segu = models.IntegerField(default=0)
    tar_hepa_trasal_terc = models.IntegerField(default=0)
    tar_hepa_estsal_prim = models.IntegerField(default=0)
    tar_hepa_estsal_segu = models.IntegerField(default=0)
    tar_hepa_estsal_terc = models.IntegerField(default=0)
    tar_hepa_trasex_prim = models.IntegerField(default=0)
    tar_hepa_trasex_segu = models.IntegerField(default=0)
    tar_hepa_trasex_terc = models.IntegerField(default=0)
    tar_hepa_pervih_prim = models.IntegerField(default=0)
    tar_hepa_pervih_segu = models.IntegerField(default=0)
    tar_hepa_pervih_terc = models.IntegerField(default=0)
    tar_hepa_perppl_prim = models.IntegerField(default=0)
    tar_hepa_perppl_segu = models.IntegerField(default=0)
    tar_hepa_perppl_terc = models.IntegerField(default=0)
    tar_hepa_otro_prim = models.IntegerField(default=0)
    tar_hepa_otro_segu = models.IntegerField(default=0)
    tar_hepa_otro_terc = models.IntegerField(default=0)
    tar_inmant = models.IntegerField(default=0)
    tar_inmanthep = models.IntegerField(default=0)
    tar_inmantrra = models.IntegerField(default=0)
    tar_tota = models.BooleanField(default=False)
    eniUser = models.ForeignKey(
        eniUser, null=True, blank=True, on_delete=models.CASCADE)

    '''@classmethod
    def get_by_month_and_user(cls, user_id, month, year):
        return cls.objects.filter(
            eniUser_id=user_id,
            tar_fech__year=year,
            tar_fech__month=month
        ).order_by('tar_fech')'''

# Crea la tabla de Esquema Regular Desperdicio


class desperdicio(models.Model):
    des_fech = models.DateField()
    des_bcg_dosapli = models.IntegerField(default=0)
    des_bcg_pervacenfabi = models.IntegerField(default=0)
    des_bcg_pervacfrasnoabi = models.IntegerField(default=0)
    des_hbpe_dosapli = models.IntegerField(default=0)
    des_hbpe_pervacenfabi = models.IntegerField(default=0)
    des_hbpe_pervacfrasnoabi = models.IntegerField(default=0)
    des_rota_dosapli = models.IntegerField(default=0)
    des_rota_pervacenfabi = models.IntegerField(default=0)
    des_rota_pervacfrasnoabi = models.IntegerField(default=0)
    des_pent_dosapli = models.IntegerField(default=0)
    des_pent_pervacenfabi = models.IntegerField(default=0)
    des_pent_pervacfrasnoabi = models.IntegerField(default=0)
    des_fipv_dosapli = models.IntegerField(default=0)
    des_fipv_pervacenfabi = models.IntegerField(default=0)
    des_fipv_pervacfrasnoabi = models.IntegerField(default=0)
    des_anti_dosapli = models.IntegerField(default=0)
    des_anti_pervacenfabi = models.IntegerField(default=0)
    des_anti_pervacfrasnoabi = models.IntegerField(default=0)
    des_neum_dosapli = models.IntegerField(default=0)
    des_neum_pervacenfabi = models.IntegerField(default=0)
    des_neum_pervacfrasnoabi = models.IntegerField(default=0)
    des_sr_dosapli = models.IntegerField(default=0)
    des_sr_pervacenfabi = models.IntegerField(default=0)
    des_sr_pervacfrasnoabi = models.IntegerField(default=0)
    des_srp_dosapli = models.IntegerField(default=0)
    des_srp_pervacenfabi = models.IntegerField(default=0)
    des_srp_pervacfrasnoabi = models.IntegerField(default=0)
    des_vari_dosapli = models.IntegerField(default=0)
    des_vari_pervacenfabi = models.IntegerField(default=0)
    des_vari_pervacfrasnoabi = models.IntegerField(default=0)
    des_fieb_dosapli = models.IntegerField(default=0)
    des_fieb_pervacenfabi = models.IntegerField(default=0)
    des_fieb_pervacfrasnoabi = models.IntegerField(default=0)
    des_dift_dosapli = models.IntegerField(default=0)
    des_dift_pervacenfabi = models.IntegerField(default=0)
    des_dift_pervacfrasnoabi = models.IntegerField(default=0)
    des_hpv_dosapli = models.IntegerField(default=0)
    des_hpv_pervacenfabi = models.IntegerField(default=0)
    des_hpv_pervacfrasnoabi = models.IntegerField(default=0)
    des_dtad_dosapli = models.IntegerField(default=0)
    des_dtad_pervacenfabi = models.IntegerField(default=0)
    des_dtad_pervacfrasnoabi = models.IntegerField(default=0)
    des_hepa_dosapli = models.IntegerField(default=0)
    des_hepa_pervacenfabi = models.IntegerField(default=0)
    des_hepa_pervacfrasnoabi = models.IntegerField(default=0)
    des_inmant_dosapli = models.IntegerField(default=0)
    des_inmant_pervacenfabi = models.IntegerField(default=0)
    des_inmant_pervacfrasnoabi = models.IntegerField(default=0)
    des_inmanthepb_dosapli = models.IntegerField(default=0)
    des_inmanthepb_pervacenfabi = models.IntegerField(default=0)
    des_inmanthepb_pervacfrasnoabi = models.IntegerField(default=0)
    des_inmantrra_dosapli = models.IntegerField(default=0)
    des_inmantrra_pervacenfabi = models.IntegerField(default=0)
    des_inmantrra_pervacfrasnoabi = models.IntegerField(default=0)
    des_infped_dosapli = models.IntegerField(default=0)
    des_infped_pervacenfabi = models.IntegerField(default=0)
    des_infped_pervacfrasnoabi = models.IntegerField(default=0)
    des_infadu_dosapli = models.IntegerField(default=0)
    des_infadu_pervacenfabi = models.IntegerField(default=0)
    des_infadu_pervacfrasnoabi = models.IntegerField(default=0)
    des_viru_dosapli = models.IntegerField(default=0)
    des_viru_pervacenfabi = models.IntegerField(default=0)
    des_viru_pervacfrasnoabi = models.IntegerField(default=0)
    des_vacsin_dosapli = models.IntegerField(default=0)
    des_vacsin_pervacenfabi = models.IntegerField(default=0)
    des_vacsin_pervacfrasnoabi = models.IntegerField(default=0)
    des_vacpfi_dosapli = models.IntegerField(default=0)
    des_vacpfi_pervacenfabi = models.IntegerField(default=0)
    des_vacpfi_pervacfrasnoabi = models.IntegerField(default=0)
    des_vacmod_dosapli = models.IntegerField(default=0)
    des_vacmod_pervacenfabi = models.IntegerField(default=0)
    des_vacmod_pervacfrasnoabi = models.IntegerField(default=0)
    des_vacvphcam_dosapli = models.IntegerField(default=0)
    des_vacvphcam_pervacenfabi = models.IntegerField(default=0)
    des_vacvphcam_pervacfrasnoabi = models.IntegerField(default=0)
    des_tota = models.BooleanField(default=False)
    eniUser = models.ForeignKey(
        'eniUser', null=True, blank=True, on_delete=models.CASCADE)

# Crea la tabla de Esquema Regular Influenza


class influenza(models.Model):
    inf_fech = models.DateField()
    inf_intr = models.IntegerField(default=0)
    inf_extr_mies_cnh = models.IntegerField(default=0)
    inf_extr_mies_cibv = models.IntegerField(default=0)
    inf_extr_mine_egen = models.IntegerField(default=0)
    inf_extr_mine_bach = models.IntegerField(default=0)
    inf_extr_visi = models.IntegerField(default=0)
    inf_extr_aten = models.IntegerField(default=0)
    inf_otro = models.IntegerField(default=0)
    inf_sexo_homb = models.IntegerField(default=0)
    inf_sexo_muje = models.IntegerField(default=0)
    inf_luga_pert = models.IntegerField(default=0)
    inf_luga_nope = models.IntegerField(default=0)
    inf_naci_ecua = models.IntegerField(default=0)
    inf_naci_colo = models.IntegerField(default=0)
    inf_naci_peru = models.IntegerField(default=0)
    inf_naci_cuba = models.IntegerField(default=0)
    inf_naci_vene = models.IntegerField(default=0)
    inf_naci_otro = models.IntegerField(default=0)
    inf_auto_indi = models.IntegerField(default=0)
    inf_auto_afro = models.IntegerField(default=0)
    inf_auto_negr = models.IntegerField(default=0)
    inf_auto_mula = models.IntegerField(default=0)
    inf_auto_mont = models.IntegerField(default=0)
    inf_auto_mest = models.IntegerField(default=0)
    inf_auto_blan = models.IntegerField(default=0)
    inf_auto_otro = models.IntegerField(default=0)
    inf_naci_achu = models.IntegerField(default=0)
    inf_naci_ando = models.IntegerField(default=0)
    inf_naci_awa = models.IntegerField(default=0)
    inf_naci_chac = models.IntegerField(default=0)
    inf_naci_cofa = models.IntegerField(default=0)
    inf_naci_eper = models.IntegerField(default=0)
    inf_naci_huan = models.IntegerField(default=0)
    inf_naci_kich = models.IntegerField(default=0)
    inf_naci_mant = models.IntegerField(default=0)
    inf_naci_seco = models.IntegerField(default=0)
    inf_naci_shiw = models.IntegerField(default=0)
    inf_naci_shua = models.IntegerField(default=0)
    inf_naci_sion = models.IntegerField(default=0)
    inf_naci_tsac = models.IntegerField(default=0)
    inf_naci_waor = models.IntegerField(default=0)
    inf_naci_zapa = models.IntegerField(default=0)
    inf_pueb_chib = models.IntegerField(default=0)
    inf_pueb_kana = models.IntegerField(default=0)
    inf_pueb_kara = models.IntegerField(default=0)
    inf_pueb_kaya = models.IntegerField(default=0)
    inf_pueb_kich = models.IntegerField(default=0)
    inf_pueb_kisa = models.IntegerField(default=0)
    inf_pueb_kitu = models.IntegerField(default=0)
    inf_pueb_nata = models.IntegerField(default=0)
    inf_pueb_otav = models.IntegerField(default=0)
    inf_pueb_palt = models.IntegerField(default=0)
    inf_pueb_panz = models.IntegerField(default=0)
    inf_pueb_past = models.IntegerField(default=0)
    inf_pueb_puru = models.IntegerField(default=0)
    inf_pueb_sala = models.IntegerField(default=0)
    inf_pueb_sara = models.IntegerField(default=0)
    inf_pueb_toma = models.IntegerField(default=0)
    inf_pueb_wara = models.IntegerField(default=0)
    inf_6a11_prim = models.IntegerField(default=0)
    inf_6a11_segu = models.IntegerField(default=0)
    inf_1ano_dosi = models.IntegerField(default=0)
    inf_2ano_dosi = models.IntegerField(default=0)
    inf_3ano_dosi = models.IntegerField(default=0)
    inf_4ano_dosi = models.IntegerField(default=0)
    inf_5ano_dosi = models.IntegerField(default=0)
    inf_6ano_dosi = models.IntegerField(default=0)
    inf_7ano_dosi = models.IntegerField(default=0)
    inf_65an_dosi = models.IntegerField(default=0)
    inf_emba_dosi = models.IntegerField(default=0)
    inf_8a64_dosi = models.IntegerField(default=0)
    inf_puer_dosi = models.IntegerField(default=0)
    inf_pers_salu_dosi = models.IntegerField(default=0)
    inf_pers_disc_dosi = models.IntegerField(default=0)
    inf_cuid_adul_dosi = models.IntegerField(default=0)
    inf_pers_cuid_dosi = models.IntegerField(default=0)
    inf_trab_avic_dosi = models.IntegerField(default=0)
    inf_ppl_dosi = models.IntegerField(default=0)
    inf_otro_ries_dosi = models.IntegerField(default=0)
    inf_pobl_gene_dosi = models.IntegerField(default=0)
    inf_tota = models.BooleanField(default=False)
    eniUser = models.ForeignKey(
        'eniUser', null=True, blank=True, on_delete=models.CASCADE)

# Crea la tabla de Admision de Registro de Paciente


class admision_datos(models.Model):
    adm_dato_admi_fech_admi = models.DateTimeField(auto_now_add=True)
    adm_dato_admi_fech_admi_actu = models.DateTimeField(auto_now=True)
    adm_dato_pers_tipo_iden = models.CharField(max_length=25, blank=True)
    adm_dato_pers_nume_iden = models.CharField(max_length=25, blank=True)
    adm_dato_pers_apel_prim = models.CharField(max_length=40, blank=True)
    adm_dato_pers_apel_segu = models.CharField(max_length=40, blank=True)
    adm_dato_pers_nomb_prim = models.CharField(max_length=40, blank=True)
    adm_dato_pers_nomb_segu = models.CharField(max_length=40, blank=True)
    adm_dato_pers_esta_civi = models.CharField(max_length=25, blank=True)
    adm_dato_pers_sexo = models.CharField(max_length=15, blank=True)
    adm_dato_pers_tele = models.CharField(max_length=15, blank=True)
    adm_dato_pers_celu = models.CharField(max_length=15, blank=True)
    adm_dato_pers_corr_elec = models.CharField(max_length=40, blank=True)
    adm_dato_naci_luga_naci = models.CharField(max_length=60, blank=True)
    adm_dato_naci_naci = models.CharField(max_length=60, blank=True)
    adm_dato_naci_fech_naci = models.DateField(blank=True, null=True)
    adm_dato_resi_pais_resi = models.CharField(max_length=60, blank=True)
    adm_dato_resi_prov = models.CharField(max_length=60, blank=True)
    adm_dato_resi_cant = models.CharField(max_length=60, blank=True)
    adm_dato_resi_parr = models.CharField(max_length=60, blank=True)
    adm_dato_resi_esta_adsc_terr = models.CharField(max_length=100, blank=True)
    adm_dato_resi_barr_sect = models.CharField(max_length=60, blank=True)
    adm_dato_resi_call_prin = models.CharField(max_length=60, blank=True)
    adm_dato_resi_call_secu = models.CharField(max_length=60, blank=True)
    adm_dato_resi_refe_resi = models.CharField(max_length=60, blank=True)
    adm_dato_auto_auto_etni = models.CharField(max_length=40, blank=True)
    adm_dato_auto_naci_etni = models.CharField(max_length=40, blank=True)
    adm_dato_auto_pueb_kich = models.CharField(max_length=40, blank=True)
    adm_dato_adic_grup_prio = models.CharField(max_length=50, blank=True)
    adm_dato_adic_nive_educ = models.CharField(max_length=40, blank=True)
    adm_dato_adic_esta_nive_educ = models.CharField(max_length=20, blank=True)
    adm_dato_adic_tipo_empr_trab = models.CharField(max_length=20, blank=True)
    adm_dato_adic_ocup_prof_prin = models.CharField(max_length=70, blank=True)
    adm_dato_adic_tipo_segu = models.CharField(max_length=40, blank=True)
    adm_dato_adic_tien_disc = models.CharField(max_length=10, blank=True)
    adm_dato_repr_tipo_iden = models.CharField(max_length=25, blank=True)
    adm_dato_repr_nume_iden = models.CharField(max_length=25, blank=True)
    adm_dato_repr_apel = models.CharField(max_length=80, blank=True)
    adm_dato_repr_nomb = models.CharField(max_length=80, blank=True)
    adm_dato_repr_fech_naci = models.DateField(blank=True, null=True)
    adm_dato_repr_pare = models.CharField(max_length=60, blank=True)
    adm_dato_repr_nume_tele = models.CharField(max_length=15, blank=True)
    adm_dato_repr_naci = models.CharField(max_length=60, blank=True)
    adm_dato_cont_enca_nece_llam = models.CharField(max_length=60, blank=True)
    adm_dato_cont_pare = models.CharField(max_length=50, blank=True)
    adm_dato_cont_dire = models.CharField(max_length=60, blank=True)
    adm_dato_cont_tele = models.CharField(max_length=15, blank=True)

    class Meta:
        unique_together = ('adm_dato_pers_tipo_iden',
                           'adm_dato_pers_nume_iden')

# Crea la tabla de Form 008 EMERGENCIA


class form_008_emergencia(models.Model):
    for_008_emer_inst_sist = models.CharField(max_length=15, blank=True)
    for_008_emer_unic = models.CharField(max_length=10, blank=True)
    for_008_emer_nomb_esta_salu = models.CharField(max_length=100, blank=True)
    for_008_emer_zona = models.CharField(max_length=10, blank=True)
    for_008_emer_prov = models.CharField(max_length=60, blank=True)
    for_008_emer_cant = models.CharField(max_length=60, blank=True)
    for_008_emer_dist = models.CharField(max_length=10, blank=True)
    for_008_emer_nive = models.CharField(max_length=10, blank=True)
    for_008_emer_fech_aten = models.DateField(blank=True, null=True)
    for_008_emer_tipo_docu_iden = models.CharField(max_length=25, blank=True)
    for_008_emer_nume_iden = models.CharField(max_length=25, blank=True)
    for_008_emer_prim_apel = models.CharField(max_length=40, blank=True)
    for_008_emer_segu_apel = models.CharField(max_length=40, blank=True)
    for_008_emer_prim_nomb = models.CharField(max_length=40, blank=True)
    for_008_emer_segu_nomb = models.CharField(max_length=40, blank=True)
    for_008_emer_sexo = models.CharField(max_length=20, blank=True)
    for_008_emer_edad = models.IntegerField(blank=True, null=True)
    for_008_emer_cond_edad = models.CharField(max_length=10, blank=True)
    for_008_emer_naci = models.CharField(max_length=60, blank=True)
    for_008_emer_etni = models.CharField(max_length=40, blank=True)
    for_008_emer_grup_prio = models.CharField(max_length=50, blank=True)
    for_008_emer_tipo_segu = models.CharField(max_length=40, blank=True)
    for_008_emer_prov_resi = models.CharField(max_length=60, blank=True)
    for_008_emer_cant_resi = models.CharField(max_length=60, blank=True)
    for_008_emer_parr_resi = models.CharField(max_length=60, blank=True)
    for_008_emer_espe_prof = models.CharField(max_length=40, blank=True)
    for_008_emer_cie_10_prin = models.CharField(max_length=10, blank=True)
    for_008_emer_diag_prin = models.CharField(max_length=260, blank=True)
    for_008_emer_cond_diag = models.CharField(max_length=50, blank=True)
    for_008_emer_cie_10_caus_exte = models.CharField(max_length=10, blank=True)
    for_008_emer_diag_caus_exte = models.CharField(max_length=260, blank=True)
    for_008_emer_hosp = models.CharField(max_length=10, blank=True)
    for_008_emer_hora_aten = models.TimeField(blank=True, null=True)
    for_008_emer_cond_alta = models.CharField(max_length=15, blank=True)
    for_008_emer_obse = models.CharField(max_length=150, blank=True)
    for_008_emer_fech_repor = models.DateTimeField(auto_now=True)
    for_008_emer_resp_aten_medi = models.CharField(max_length=80, blank=True)
    for_008_emer_apoy_aten_medi = models.CharField(max_length=80, blank=True)
    for_008_emer_edad_gest = models.DecimalField(
        max_digits=4,
        decimal_places=1,
        blank=True,
        null=True,
        help_text='Edad gestacional en semanas (ej: 38,5)'
    )
    for_008_emer_ries_obst = models.CharField(max_length=15, blank=True)
    for_008_emer_indi_paci_fami = models.CharField(max_length=150, blank=True)
    for_008_emer_unid_salu_resp_segu_aten = models.CharField(
        max_length=100, blank=True)
    for_008_emer_dire_domi = models.CharField(max_length=300, blank=True)
    for_008_emer_tele_paci = models.CharField(max_length=30, blank=True)
    admision_datos = models.ForeignKey(
        'admision_datos',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='formularios_008_emergencia',
        help_text='Datos de admisión del paciente'
    )

    class Meta:
        verbose_name = 'Formulario 008 Emergencia'
        verbose_name_plural = 'Formularios 008 Emergencia'
        ordering = ['-for_008_emer_fech_aten']
        indexes = [
            models.Index(fields=['for_008_emer_nume_iden']),
            models.Index(fields=['for_008_emer_fech_aten']),
        ]

    def __str__(self):
        return f"Form 008 - {self.for_008_emer_prim_nomb} {self.for_008_emer_prim_apel} - {self.for_008_emer_fech_aten}"

    def get_nombre_completo(self):
        """Retorna el nombre completo del paciente"""
        nombres = f"{self.for_008_emer_prim_nomb or ''} {self.for_008_emer_segu_nomb or ''}".strip()
        apellidos = f"{self.for_008_emer_prim_apel or ''} {self.for_008_emer_segu_apel or ''}".strip()
        return f"{nombres} {apellidos}".strip()

    def clean(self):
        """Validaciones esenciales a nivel de modelo"""
        from django.core.exceptions import ValidationError

        # Solo validaciones críticas que afectan la integridad de los datos
        if self.for_008_emer_edad is not None and self.for_008_emer_edad < 0:
            raise ValidationError('La edad no puede ser negativa')

# Crea la tabla de Reporte de ENI


class reporte_eni(models.Model):
    rep_fech = models.DateField()
    rep_inf_sal_ant_bcg = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_bcg = models.IntegerField(default=0)
    rep_inf_ing_con_fis_bcg = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_bcg = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_bcg = models.IntegerField(default=0)
    rep_inf_tot_dis_bcg = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_bcg = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_bcg = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_bcg = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_bcg = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_bcg = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_bcg = models.IntegerField(default=0)
    rep_inf_sal_mes_bcg = models.IntegerField(default=0)
    rep_sol_nec_mes_bcg = models.IntegerField(default=0)
    rep_sol_sol_mes_bcg = models.IntegerField(default=0)
    rep_con_lot_bio_bcg = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_bcg = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_pent = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_pent = models.IntegerField(default=0)
    rep_inf_ing_con_fis_pent = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_pent = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_pent = models.IntegerField(default=0)
    rep_inf_tot_dis_pent = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_pent = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_pent = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_pent = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_pent = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_pent = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_pent = models.IntegerField(default=0)
    rep_inf_sal_mes_pent = models.IntegerField(default=0)
    rep_sol_nec_mes_pent = models.IntegerField(default=0)
    rep_sol_sol_mes_pent = models.IntegerField(default=0)
    rep_con_lot_bio_pent = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_pent = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_neum = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_neum = models.IntegerField(default=0)
    rep_inf_ing_con_fis_neum = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_neum = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_neum = models.IntegerField(default=0)
    rep_inf_tot_dis_neum = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_neum = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_neum = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_neum = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_neum = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_neum = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_neum = models.IntegerField(default=0)
    rep_inf_sal_mes_neum = models.IntegerField(default=0)
    rep_sol_nec_mes_neum = models.IntegerField(default=0)
    rep_sol_sol_mes_neum = models.IntegerField(default=0)
    rep_con_lot_bio_neum = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_neum = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_anti = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_anti = models.IntegerField(default=0)
    rep_inf_ing_con_fis_anti = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_anti = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_anti = models.IntegerField(default=0)
    rep_inf_tot_dis_anti = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_anti = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_anti = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_anti = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_anti = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_anti = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_anti = models.IntegerField(default=0)
    rep_inf_sal_mes_anti = models.IntegerField(default=0)
    rep_sol_nec_mes_anti = models.IntegerField(default=0)
    rep_sol_sol_mes_anti = models.IntegerField(default=0)
    rep_con_lot_bio_anti = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_anti = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_fipv = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_fipv = models.IntegerField(default=0)
    rep_inf_ing_con_fis_fipv = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_fipv = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_fipv = models.IntegerField(default=0)
    rep_inf_tot_dis_fipv = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_fipv = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_fipv = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_fipv = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_fipv = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_fipv = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_fipv = models.IntegerField(default=0)
    rep_inf_sal_mes_fipv = models.IntegerField(default=0)
    rep_sol_nec_mes_fipv = models.IntegerField(default=0)
    rep_sol_sol_mes_fipv = models.IntegerField(default=0)
    rep_con_lot_bio_fipv = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_fipv = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_rota = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_rota = models.IntegerField(default=0)
    rep_inf_ing_con_fis_rota = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_rota = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_rota = models.IntegerField(default=0)
    rep_inf_tot_dis_rota = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_rota = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_rota = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_rota = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_rota = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_rota = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_rota = models.IntegerField(default=0)
    rep_inf_sal_mes_rota = models.IntegerField(default=0)
    rep_sol_nec_mes_rota = models.IntegerField(default=0)
    rep_sol_sol_mes_rota = models.IntegerField(default=0)
    rep_con_lot_bio_rota = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_rota = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_srp = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_srp = models.IntegerField(default=0)
    rep_inf_ing_con_fis_srp = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_srp = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_srp = models.IntegerField(default=0)
    rep_inf_tot_dis_srp = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_srp = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_srp = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_srp = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_srp = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_srp = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_srp = models.IntegerField(default=0)
    rep_inf_sal_mes_srp = models.IntegerField(default=0)
    rep_sol_nec_mes_srp = models.IntegerField(default=0)
    rep_sol_sol_mes_srp = models.IntegerField(default=0)
    rep_con_lot_bio_srp = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_srp = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_fieb = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_fieb = models.IntegerField(default=0)
    rep_inf_ing_con_fis_fieb = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_fieb = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_fieb = models.IntegerField(default=0)
    rep_inf_tot_dis_fieb = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_fieb = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_fieb = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_fieb = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_fieb = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_fieb = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_fieb = models.IntegerField(default=0)
    rep_inf_sal_mes_fieb = models.IntegerField(default=0)
    rep_sol_nec_mes_fieb = models.IntegerField(default=0)
    rep_sol_sol_mes_fieb = models.IntegerField(default=0)
    rep_con_lot_bio_fieb = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_fieb = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_vari = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_vari = models.IntegerField(default=0)
    rep_inf_ing_con_fis_vari = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_vari = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_vari = models.IntegerField(default=0)
    rep_inf_tot_dis_vari = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_vari = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_vari = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_vari = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_vari = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_vari = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_vari = models.IntegerField(default=0)
    rep_inf_sal_mes_vari = models.IntegerField(default=0)
    rep_sol_nec_mes_vari = models.IntegerField(default=0)
    rep_sol_sol_mes_vari = models.IntegerField(default=0)
    rep_con_lot_bio_vari = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_vari = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_sr = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_sr = models.IntegerField(default=0)
    rep_inf_ing_con_fis_sr = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_sr = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_sr = models.IntegerField(default=0)
    rep_inf_tot_dis_sr = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_sr = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_sr = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_sr = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_sr = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_sr = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_sr = models.IntegerField(default=0)
    rep_inf_sal_mes_sr = models.IntegerField(default=0)
    rep_sol_nec_mes_sr = models.IntegerField(default=0)
    rep_sol_sol_mes_sr = models.IntegerField(default=0)
    rep_con_lot_bio_sr = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_sr = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_dift = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_dift = models.IntegerField(default=0)
    rep_inf_ing_con_fis_dift = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_dift = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_dift = models.IntegerField(default=0)
    rep_inf_tot_dis_dift = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_dift = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_dift = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_dift = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_dift = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_dift = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_dift = models.IntegerField(default=0)
    rep_inf_sal_mes_dift = models.IntegerField(default=0)
    rep_sol_nec_mes_dift = models.IntegerField(default=0)
    rep_sol_sol_mes_dift = models.IntegerField(default=0)
    rep_con_lot_bio_dift = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_dift = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_dtad = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_dtad = models.IntegerField(default=0)
    rep_inf_ing_con_fis_dtad = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_dtad = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_dtad = models.IntegerField(default=0)
    rep_inf_tot_dis_dtad = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_dtad = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_dtad = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_dtad = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_dtad = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_dtad = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_dtad = models.IntegerField(default=0)
    rep_inf_sal_mes_dtad = models.IntegerField(default=0)
    rep_sol_nec_mes_dtad = models.IntegerField(default=0)
    rep_sol_sol_mes_dtad = models.IntegerField(default=0)
    rep_con_lot_bio_dtad = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_dtad = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_hpv = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_hpv = models.IntegerField(default=0)
    rep_inf_ing_con_fis_hpv = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_hpv = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_hpv = models.IntegerField(default=0)
    rep_inf_tot_dis_hpv = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_hpv = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_hpv = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_hpv = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_hpv = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_hpv = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_hpv = models.IntegerField(default=0)
    rep_inf_sal_mes_hpv = models.IntegerField(default=0)
    rep_sol_nec_mes_hpv = models.IntegerField(default=0)
    rep_sol_sol_mes_hpv = models.IntegerField(default=0)
    rep_con_lot_bio_hpv = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_hpv = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_hepa = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_hepa = models.IntegerField(default=0)
    rep_inf_ing_con_fis_hepa = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_hepa = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_hepa = models.IntegerField(default=0)
    rep_inf_tot_dis_hepa = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_hepa = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_hepa = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_hepa = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_hepa = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_hepa = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_hepa = models.IntegerField(default=0)
    rep_inf_sal_mes_hepa = models.IntegerField(default=0)
    rep_sol_nec_mes_hepa = models.IntegerField(default=0)
    rep_sol_sol_mes_hepa = models.IntegerField(default=0)
    rep_con_lot_bio_hepa = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_hepa = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_hbpe = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_hbpe = models.IntegerField(default=0)
    rep_inf_ing_con_fis_hbpe = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_hbpe = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_hbpe = models.IntegerField(default=0)
    rep_inf_tot_dis_hbpe = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_hbpe = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_hbpe = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_hbpe = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_hbpe = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_hbpe = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_hbpe = models.IntegerField(default=0)
    rep_inf_sal_mes_hbpe = models.IntegerField(default=0)
    rep_sol_nec_mes_hbpe = models.IntegerField(default=0)
    rep_sol_sol_mes_hbpe = models.IntegerField(default=0)
    rep_con_lot_bio_hbpe = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_hbpe = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_infped = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_infped = models.IntegerField(default=0)
    rep_inf_ing_con_fis_infped = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_infped = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_infped = models.IntegerField(default=0)
    rep_inf_tot_dis_infped = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_infped = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_infped = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_infped = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_infped = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_infped = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_infped = models.IntegerField(default=0)
    rep_inf_sal_mes_infped = models.IntegerField(default=0)
    rep_sol_nec_mes_infped = models.IntegerField(default=0)
    rep_sol_sol_mes_infped = models.IntegerField(default=0)
    rep_con_lot_bio_infped = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_infped = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_infadu = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_infadu = models.IntegerField(default=0)
    rep_inf_ing_con_fis_infadu = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_infadu = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_infadu = models.IntegerField(default=0)
    rep_inf_tot_dis_infadu = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_infadu = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_infadu = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_infadu = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_infadu = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_infadu = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_infadu = models.IntegerField(default=0)
    rep_inf_sal_mes_infadu = models.IntegerField(default=0)
    rep_sol_nec_mes_infadu = models.IntegerField(default=0)
    rep_sol_sol_mes_infadu = models.IntegerField(default=0)
    rep_con_lot_bio_infadu = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_infadu = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_pfiz = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_pfiz = models.IntegerField(default=0)
    rep_inf_ing_con_fis_pfiz = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_pfiz = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_pfiz = models.IntegerField(default=0)
    rep_inf_tot_dis_pfiz = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_pfiz = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_pfiz = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_pfiz = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_pfiz = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_pfiz = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_pfiz = models.IntegerField(default=0)
    rep_inf_sal_mes_pfiz = models.IntegerField(default=0)
    rep_sol_nec_mes_pfiz = models.IntegerField(default=0)
    rep_sol_sol_mes_pfiz = models.IntegerField(default=0)
    rep_con_lot_bio_pfiz = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_pfiz = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_sino = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_sino = models.IntegerField(default=0)
    rep_inf_ing_con_fis_sino = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_sino = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_sino = models.IntegerField(default=0)
    rep_inf_tot_dis_sino = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_sino = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_sino = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_sino = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_sino = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_sino = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_sino = models.IntegerField(default=0)
    rep_inf_sal_mes_sino = models.IntegerField(default=0)
    rep_sol_nec_mes_sino = models.IntegerField(default=0)
    rep_sol_sol_mes_sino = models.IntegerField(default=0)
    rep_con_lot_bio_sino = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_sino = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_cans = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_cans = models.IntegerField(default=0)
    rep_inf_ing_con_fis_cans = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_cans = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_cans = models.IntegerField(default=0)
    rep_inf_tot_dis_cans = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_cans = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_cans = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_cans = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_cans = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_cans = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_cans = models.IntegerField(default=0)
    rep_inf_sal_mes_cans = models.IntegerField(default=0)
    rep_sol_nec_mes_cans = models.IntegerField(default=0)
    rep_sol_sol_mes_cans = models.IntegerField(default=0)
    rep_con_lot_bio_cans = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_cans = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_astr = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_astr = models.IntegerField(default=0)
    rep_inf_ing_con_fis_astr = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_astr = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_astr = models.IntegerField(default=0)
    rep_inf_tot_dis_astr = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_astr = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_astr = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_astr = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_astr = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_astr = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_astr = models.IntegerField(default=0)
    rep_inf_sal_mes_astr = models.IntegerField(default=0)
    rep_sol_nec_mes_astr = models.IntegerField(default=0)
    rep_sol_sol_mes_astr = models.IntegerField(default=0)
    rep_con_lot_bio_astr = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_astr = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_modr = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_modr = models.IntegerField(default=0)
    rep_inf_ing_con_fis_modr = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_modr = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_modr = models.IntegerField(default=0)
    rep_inf_tot_dis_modr = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_modr = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_modr = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_modr = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_modr = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_modr = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_modr = models.IntegerField(default=0)
    rep_inf_sal_mes_modr = models.IntegerField(default=0)
    rep_sol_nec_mes_modr = models.IntegerField(default=0)
    rep_sol_sol_mes_modr = models.IntegerField(default=0)
    rep_con_lot_bio_modr = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_modr = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_virsim = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_virsim = models.IntegerField(default=0)
    rep_inf_ing_con_fis_virsim = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_virsim = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_virsim = models.IntegerField(default=0)
    rep_inf_tot_dis_virsim = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_virsim = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_virsim = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_virsim = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_virsim = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_virsim = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_virsim = models.IntegerField(default=0)
    rep_inf_sal_mes_virsim = models.IntegerField(default=0)
    rep_sol_nec_mes_virsim = models.IntegerField(default=0)
    rep_sol_sol_mes_virsim = models.IntegerField(default=0)
    rep_con_lot_bio_virsim = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_virsim = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_vacvphcam = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_vacvphcam = models.IntegerField(default=0)
    rep_inf_ing_con_fis_vacvphcam = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_vacvphcam = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_vacvphcam = models.IntegerField(default=0)
    rep_inf_tot_dis_vacvphcam = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_vacvphcam = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_vacvphcam = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_vacvphcam = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_vacvphcam = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_vacvphcam = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_vacvphcam = models.IntegerField(default=0)
    rep_inf_sal_mes_vacvphcam = models.IntegerField(default=0)
    rep_sol_nec_mes_vacvphcam = models.IntegerField(default=0)
    rep_sol_sol_mes_vacvphcam = models.IntegerField(default=0)
    rep_con_lot_bio_vacvphcam = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_vacvphcam = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_inm_anti = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_inm_anti = models.IntegerField(default=0)
    rep_inf_ing_con_fis_inm_anti = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_inm_anti = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_inm_anti = models.IntegerField(default=0)
    rep_inf_tot_dis_inm_anti = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_inm_anti = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_inm_anti = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_inm_anti = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_inm_anti = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_inm_anti = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_inm_anti = models.IntegerField(default=0)
    rep_inf_sal_mes_inm_anti = models.IntegerField(default=0)
    rep_sol_nec_mes_inm_anti = models.IntegerField(default=0)
    rep_sol_sol_mes_inm_anti = models.IntegerField(default=0)
    rep_con_lot_bio_inm_anti = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_inm_anti = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_inm_ant_hep_b = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_inm_ant_hep_b = models.IntegerField(default=0)
    rep_inf_ing_con_fis_inm_ant_hep_b = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_inm_ant_hep_b = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_inm_ant_hep_b = models.IntegerField(default=0)
    rep_inf_tot_dis_inm_ant_hep_b = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_inm_ant_hep_b = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_inm_ant_hep_b = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_inm_ant_hep_b = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_inm_ant_hep_b = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_inm_ant_hep_b = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_inm_ant_hep_b = models.IntegerField(default=0)
    rep_inf_sal_mes_inm_ant_hep_b = models.IntegerField(default=0)
    rep_sol_nec_mes_inm_ant_hep_b = models.IntegerField(default=0)
    rep_sol_sol_mes_inm_ant_hep_b = models.IntegerField(default=0)
    rep_con_lot_bio_inm_ant_hep_b = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_inm_ant_hep_b = models.CharField(
        max_length=100, blank=True)
    rep_inf_sal_ant_inm_ant_rrab = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_inm_ant_rrab = models.IntegerField(default=0)
    rep_inf_ing_con_fis_inm_ant_rrab = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_inm_ant_rrab = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_inm_ant_rrab = models.IntegerField(default=0)
    rep_inf_tot_dis_inm_ant_rrab = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_inm_ant_rrab = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_inm_ant_rrab = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_inm_ant_rrab = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_inm_ant_rrab = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_inm_ant_rrab = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_inm_ant_rrab = models.IntegerField(default=0)
    rep_inf_sal_mes_inm_ant_rrab = models.IntegerField(default=0)
    rep_sol_nec_mes_inm_ant_rrab = models.IntegerField(default=0)
    rep_sol_sol_mes_inm_ant_rrab = models.IntegerField(default=0)
    rep_con_lot_bio_inm_ant_rrab = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_inm_ant_rrab = models.CharField(max_length=100, blank=True)
    rep_inf_sal_ant_caj_bios = models.IntegerField(default=0)
    rep_inf_ing_ban_vac_caj_bios = models.IntegerField(default=0)
    rep_inf_ing_con_fis_caj_bios = models.IntegerField(default=0)
    rep_inf_ing_rec_otr_caj_bios = models.IntegerField(default=0)
    rep_inf_ing_tot_ing_caj_bios = models.IntegerField(default=0)
    rep_inf_tot_dis_caj_bios = models.IntegerField(default=0)
    rep_inf_egr_apl_mes_caj_bios = models.IntegerField(default=0)
    rep_inf_egr_per_vac_abi_caj_bios = models.IntegerField(default=0)
    rep_inf_egr_per_vac_noa_caj_bios = models.IntegerField(default=0)
    rep_inf_egr_tra_otr_caj_bios = models.IntegerField(default=0)
    rep_inf_egr_dev_ban_caj_bios = models.IntegerField(default=0)
    rep_inf_egr_tot_dos_caj_bios = models.IntegerField(default=0)
    rep_inf_sal_mes_caj_bios = models.IntegerField(default=0)
    rep_sol_nec_mes_caj_bios = models.IntegerField(default=0)
    rep_sol_sol_mes_caj_bios = models.IntegerField(default=0)
    rep_con_lot_bio_caj_bios = models.CharField(max_length=80, blank=True)
    rep_con_fec_cad_caj_bios = models.CharField(max_length=100, blank=True)
    rep_eni = models.BooleanField(default=False)
    eniUser = models.ForeignKey(
        'eniUser', null=True, blank=True, on_delete=models.CASCADE)

# Crea la tabla de Registro de Vacunados


class registro_vacunado(models.Model):
    vac_reg_ano_mes_dia_apli = models.DateField()
    vac_reg_punt_vacu = models.CharField(max_length=40, blank=True)
    vac_reg_unic_esta = models.CharField(max_length=8, blank=True)
    vac_reg_nomb_esta_salu = models.CharField(max_length=40, blank=True)
    vac_reg_zona = models.CharField(max_length=8, blank=True)
    vac_reg_dist = models.CharField(max_length=8, blank=True)
    vac_reg_prov = models.CharField(max_length=20, blank=True)
    vac_reg_cant = models.CharField(max_length=30, blank=True)
    vac_reg_apel = models.CharField(max_length=40, blank=True)
    vac_reg_nomb = models.CharField(max_length=40, blank=True)
    vac_reg_tipo_iden = models.CharField(max_length=30, blank=True)
    vac_reg_nume_iden = models.CharField(max_length=20, blank=True)
    vac_reg_sexo = models.CharField(max_length=10, blank=True)
    vac_reg_ano_mes_dia_naci = models.DateField()
    vac_reg_naci = models.CharField(max_length=30, blank=True)
    vac_reg_etni = models.CharField(max_length=20, blank=True)
    vac_reg_naci_etni = models.CharField(max_length=30, blank=True)
    vac_reg_pueb = models.CharField(max_length=30, blank=True)
    vac_reg_resi_prov = models.CharField(max_length=20, blank=True)
    vac_reg_resi_cant = models.CharField(max_length=30, blank=True)
    vac_reg_resi_parr = models.CharField(max_length=40, blank=True)
    vac_reg_teld_cont = models.CharField(max_length=15, blank=True)
    vac_reg_corr_elec = models.CharField(max_length=40, blank=True)
    vac_reg_grup_ries = models.CharField(max_length=40, blank=True)
    vac_reg_fase_vacu = models.IntegerField(default=0)
    vac_reg_esta_vacu = models.CharField(max_length=15, blank=True)
    vac_reg_tipo_esqu = models.CharField(max_length=30, blank=True)
    vac_reg_vacu = models.CharField(max_length=40, blank=True)
    vac_reg_lote_vacu = models.CharField(max_length=20, blank=True)
    vac_reg_dosi_apli = models.IntegerField(default=0)
    vac_reg_paci_agen = models.CharField(max_length=8, blank=True)
    vac_reg_nomb_vacu = models.CharField(max_length=40, blank=True)
    vac_reg_iden_vacu = models.CharField(max_length=20, blank=True)
    vac_reg_nomb_prof_regi = models.CharField(max_length=40, blank=True)
    vac_reg_reci_dosi_prev_exte = models.CharField(max_length=8, blank=True)
    vac_reg_nomb_dosi_exte = models.CharField(max_length=40, blank=True)
    vac_reg_fech_anio_mes_dia_dosi_exte = models.DateField()
    vac_reg_pais_dosi_exte = models.CharField(max_length=30, blank=True)
    vac_reg_lote_dosi_exte = models.CharField(max_length=20, blank=True)
    eniUser = models.ForeignKey(
        'eniUser', null=True, blank=True, on_delete=models.CASCADE)
