# Generated by Django 5.1.1 on 2024-09-14 07:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='eniUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fun_sex', models.CharField(blank=True, max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='desperdicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_fech', models.DateField()),
                ('des_bcg_dosapli', models.IntegerField(blank=True)),
                ('des_bcg_pervacenfabi', models.IntegerField(blank=True)),
                ('des_bcg_pervacfrasnoabi', models.IntegerField(blank=True)),
                ('des_tota', models.BooleanField(default=False)),
                ('eniUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tardio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tar_fech', models.DateField()),
                ('tar_intr', models.IntegerField(blank=True)),
                ('tar_extr_mies_cnh', models.IntegerField(blank=True)),
                ('tar_1ano_1rad_fipv', models.IntegerField(blank=True)),
                ('tar_1ano_1rad_hbpe', models.IntegerField(blank=True)),
                ('tar_1ano_1rad_dpt', models.IntegerField(blank=True)),
                ('tar_1ano_2dad_fipv', models.IntegerField(blank=True)),
                ('tar_tota', models.BooleanField(default=False)),
                ('eniUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='temprano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_fech', models.DateField()),
                ('tem_intr', models.IntegerField(blank=True)),
                ('tem_extr_mies_cnh', models.IntegerField(blank=True)),
                ('tem_men1_dosi_bcgp', models.IntegerField(blank=True)),
                ('tem_men1_dosi_hbpr', models.IntegerField(blank=True)),
                ('tem_men1_dosi_bcgd', models.IntegerField(blank=True)),
                ('tem_tota', models.BooleanField(default=False)),
                ('eniUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='unidadSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_zona', models.CharField(blank=True, max_length=10)),
                ('uni_dist', models.CharField(blank=True, max_length=8)),
                ('uni_prov', models.CharField(blank=True, max_length=20)),
                ('uni_cant', models.CharField(blank=True, max_length=30)),
                ('uni_parr', models.CharField(blank=True, max_length=40)),
                ('uni_unic', models.CharField(blank=True, max_length=8)),
                ('uni_unid', models.CharField(blank=True, max_length=40)),
                ('uni_tipo', models.CharField(blank=True, max_length=30)),
                ('uni_nive', models.CharField(blank=True, max_length=8)),
                ('eniUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
