# Generated by Django 5.1.1 on 2024-11-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eniuser',
            name='fun_admi_rol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidad_salud',
            name='uni_cant',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='unidad_salud',
            name='uni_dist',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='unidad_salud',
            name='uni_nive',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='unidad_salud',
            name='uni_parr',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='unidad_salud',
            name='uni_prov',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unidad_salud',
            name='uni_tipo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='unidad_salud',
            name='uni_zona',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
