# Generated by Django 5.1.1 on 2025-07-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admision_datos',
            name='adm_dato_repr_fech_naci',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admision_datos',
            name='adm_dato_repr_naci',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_esta_nive_educ',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_nive_educ',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_ocup_prof_prin',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_tien_disc',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_tipo_empr_trab',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_tipo_segu',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_auto_auto_etni',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_auto_naci_etni',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_auto_pueb_kich',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_cont_pare',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_naci_luga_naci',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_naci_naci',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_pers_apel_prim',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_pers_apel_segu',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_pers_esta_civi',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_pers_nomb_prim',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_pers_nomb_segu',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_pers_nume_iden',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_pers_tipo_iden',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_apel',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_nomb',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_nume_iden',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_tipo_iden',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_barr_sect',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_call_prin',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_call_secu',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_cant',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_pais_resi',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_parr',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_prov',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
