# Generated by Django 5.1.1 on 2024-10-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eniuser',
            name='fun_titu',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
