# Generated by Django 5.1.1 on 2025-07-09 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0002_admision_datos_adm_dato_repr_fech_naci_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='admision_datos',
            unique_together={('adm_dato_pers_tipo_iden', 'adm_dato_pers_nume_iden')},
        ),
        migrations.CreateModel(
            name='form_008_emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_008_emer_inst_sist', models.CharField(blank=True, max_length=15)),
                ('for_008_emer_unic', models.CharField(blank=True, max_length=10)),
                ('for_008_emer_nomb_esta_salu', models.CharField(blank=True, max_length=100)),
                ('for_008_emer_zona', models.CharField(blank=True, max_length=10)),
                ('for_008_emer_prov', models.CharField(blank=True, max_length=60)),
                ('for_008_emer_cant', models.CharField(blank=True, max_length=60)),
                ('for_008_emer_dist', models.CharField(blank=True, max_length=10)),
                ('for_008_emer_nive', models.CharField(blank=True, max_length=10)),
                ('for_008_emer_fech_aten', models.DateField(blank=True, null=True)),
                ('for_008_emer_tipo_docu_iden', models.CharField(blank=True, max_length=25)),
                ('for_008_emer_nume_iden', models.CharField(blank=True, max_length=25)),
                ('for_008_emer_prim_apel', models.CharField(blank=True, max_length=40)),
                ('for_008_emer_segu_apel', models.CharField(blank=True, max_length=40)),
                ('for_008_emer_prim_nomb', models.CharField(blank=True, max_length=40)),
                ('for_008_emer_segu_nomb', models.CharField(blank=True, max_length=40)),
                ('for_008_emer_sexo', models.CharField(blank=True, max_length=20)),
                ('for_008_emer_edad', models.IntegerField(blank=True, null=True)),
                ('for_008_emer_cond_edad', models.CharField(blank=True, max_length=10)),
                ('for_008_emer_naci', models.CharField(blank=True, max_length=60)),
                ('for_008_emer_etni', models.CharField(blank=True, max_length=40)),
                ('for_008_emer_grup_prio', models.CharField(blank=True, max_length=50)),
                ('for_008_emer_tipo_segu', models.CharField(blank=True, max_length=40)),
                ('for_008_emer_prov_reci', models.CharField(blank=True, max_length=60)),
                ('for_008_emer_cant_reci', models.CharField(blank=True, max_length=60)),
                ('for_008_emer_parr_reci', models.CharField(blank=True, max_length=60)),
                ('for_008_emer_espe_prof', models.CharField(blank=True, max_length=40)),
                ('for_008_emer_cie_10_prin', models.CharField(blank=True, max_length=10)),
                ('for_008_emer_diga_prin', models.CharField(blank=True, max_length=260)),
                ('for_008_emer_cond_diag', models.CharField(blank=True, max_length=50)),
                ('for_008_emer_cie_10_caus_exte', models.CharField(blank=True, max_length=10)),
                ('for_008_emer_diag_caus_exte', models.CharField(blank=True, max_length=260)),
                ('for_008_emer_hosp', models.CharField(blank=True, max_length=10)),
                ('for_008_emer_hora_aten', models.TimeField(blank=True, null=True)),
                ('for_008_emer_cond_alta', models.CharField(blank=True, max_length=15)),
                ('for_008_emer_obse', models.CharField(blank=True, max_length=100)),
                ('for_008_emer_resp_aten_medi', models.CharField(blank=True, max_length=80)),
                ('for_008_emer_apoy_aten_medi', models.CharField(blank=True, max_length=80)),
                ('admision_datos', models.ForeignKey(blank=True, help_text='Datos de admisión del paciente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_008_emergencia', to='eni.admision_datos')),
            ],
            options={
                'verbose_name': 'Formulario 008 Emergencia',
                'verbose_name_plural': 'Formularios 008 Emergencia',
                'ordering': ['-for_008_emer_fech_aten'],
                'indexes': [models.Index(fields=['for_008_emer_nume_iden'], name='eni_form_00_for_008_dc6589_idx'), models.Index(fields=['for_008_emer_fech_aten'], name='eni_form_00_for_008_015342_idx')],
            },
        ),
    ]
