# Generated by Django 5.1.1 on 2024-11-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0002_eniuser_fun_admi_rol_alter_unidad_salud_uni_cant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_auto_etni',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_esta_nive_educ',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_naci_etni',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_nive_educ',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_ocup_prin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_pueb_kich',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_segu_salu_prin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_segu_salu_secu',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_tien_disc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_tipo_bono_reci',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_tipo_empr_trab',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_cont_dire',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_cont_enca_nece_llam',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_cont_pare',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_cont_tele',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_naci_cant',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_naci_fech_naci',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_naci_luga_naci',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_naci_naci',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_naci_parr',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_naci_prov',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_pers_celu',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_pers_corr_elec',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_pers_esta_civi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_pers_tele',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_apel',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_naci',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_nomb',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_nume_iden',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_nume_tele',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_pare',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_reci_bono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_tipo_iden',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_barr',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_call_prin',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_call_secu',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_cant',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_nume',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_pais_resi',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_parr',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_prov',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_refe_resi',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
