# Generated by Django 5.1.1 on 2024-11-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0003_alter_admision_datos_adm_dato_adic_auto_etni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_pers_celu',
            field=models.CharField(blank=True, default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_pers_esta_civi',
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_pers_tele',
            field=models.CharField(blank=True, default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidad_salud',
            name='uni_cant',
            field=models.CharField(blank=True, default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidad_salud',
            name='uni_dist',
            field=models.CharField(blank=True, default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidad_salud',
            name='uni_nive',
            field=models.CharField(blank=True, default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidad_salud',
            name='uni_parr',
            field=models.CharField(blank=True, default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidad_salud',
            name='uni_prov',
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidad_salud',
            name='uni_tipo',
            field=models.CharField(blank=True, default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidad_salud',
            name='uni_zona',
            field=models.CharField(blank=True, default=0, max_length=10),
            preserve_default=False,
        ),
    ]
