# Generated by Django 5.1.1 on 2025-07-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0003_alter_admision_datos_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_008_emergencia',
            name='for_008_emer_dire_domi',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='form_008_emergencia',
            name='for_008_emer_edad_gest',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Edad gestacional en semanas (ej: 38.5)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='form_008_emergencia',
            name='for_008_emer_indi_paci_fami',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='form_008_emergencia',
            name='for_008_emer_ries_obst',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='form_008_emergencia',
            name='for_008_emer_tele_paci',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='form_008_emergencia',
            name='for_008_emer_unid_salu_resp_segu_aten',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='form_008_emergencia',
            name='for_008_emer_obse',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
