# Generated by Django 5.1.1 on 2025-07-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0004_form_008_emergencia_for_008_emer_dire_domi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admision_datos',
            name='adm_dato_resi_esta_adsc_terr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
