# Generated by Django 5.1.1 on 2024-11-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0004_alter_admision_datos_adm_dato_pers_celu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_auto_etni',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_esta_nive_educ',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_naci_etni',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_nive_educ',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_ocup_prin',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_pueb_kich',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_segu_salu_prin',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_segu_salu_secu',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_tien_disc',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_tipo_bono_reci',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_adic_tipo_empr_trab',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_cont_dire',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_cont_enca_nece_llam',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_cont_pare',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_cont_tele',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_naci_cant',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_naci_fech_naci',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_naci_luga_naci',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_naci_naci',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_naci_parr',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_naci_prov',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_pers_corr_elec',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_apel',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_naci',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_nomb',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_nume_iden',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_nume_tele',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_pare',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_reci_bono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_tipo_iden',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_barr',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_call_prin',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_call_secu',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_cant',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_nume',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_pais_resi',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_parr',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_prov',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_refe_resi',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='eniuser',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='eniuser',
            name='fun_admi_rol',
            field=models.IntegerField(blank=True),
        ),
    ]
