# Generated by Django 5.1.1 on 2024-11-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0005_alter_admision_datos_adm_dato_adic_auto_etni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_naci_fech_naci',
            field=models.DateField(blank=True, null=True),
        ),
    ]
