# Generated by Django 5.1.1 on 2025-07-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0006_rename_for_008_emer_diga_prin_form_008_emergencia_for_008_emer_diag_prin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_008_emergencia',
            old_name='for_008_emer_cant_reci',
            new_name='for_008_emer_cant_resi',
        ),
        migrations.RenameField(
            model_name='form_008_emergencia',
            old_name='for_008_emer_parr_reci',
            new_name='for_008_emer_parr_resi',
        ),
        migrations.RenameField(
            model_name='form_008_emergencia',
            old_name='for_008_emer_prov_reci',
            new_name='for_008_emer_prov_resi',
        ),
    ]
