# Generated by Django 5.1.1 on 2024-11-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0007_alter_unidad_salud_eniuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eniuser',
            name='fun_admi_rol',
            field=models.IntegerField(default=0),
        ),
    ]
