# Generated by Django 5.1.1 on 2025-07-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0007_rename_for_008_emer_cant_reci_form_008_emergencia_for_008_emer_cant_resi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad_salud',
            name='uni_inst_sist',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
