# Generated by Django 5.1.1 on 2025-07-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0008_unidad_salud_uni_inst_sist'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_008_emergencia',
            name='for_008_emer_fech_repor',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_admi_fech_admi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_admi_fech_admi_actu',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
