# Generated by Django 5.1.1 on 2024-11-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0008_alter_eniuser_fun_admi_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_pers_corr_elec',
            field=models.EmailField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='eniuser',
            name='email',
            field=models.EmailField(blank=True, max_length=40),
        ),
    ]
