# Generated by Django 5.1.1 on 2025-07-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0009_form_008_emergencia_for_008_emer_fech_repor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad_salud',
            name='uni_unid_prin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
