# Generated by Django 5.1.1 on 2025-07-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0010_unidad_salud_uni_unid_prin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_008_emergencia',
            name='for_008_emer_indi_paci_fami',
        ),
        migrations.AlterField(
            model_name='form_008_emergencia',
            name='for_008_emer_edad_gest',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Edad gestacional en semanas (ej: 38.5)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='form_008_emergencia',
            name='for_008_emer_obse',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
