# Generated by Django 5.1.1 on 2025-07-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0011_remove_form_008_emergencia_for_008_emer_indi_paci_fami_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_008_emergencia',
            name='for_008_emer_paci_falt_dato',
            field=models.IntegerField(default=0),
        ),
    ]
