# Generated by Django 5.1.1 on 2025-07-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0012_form_008_emergencia_for_008_emer_paci_falt_dato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_008_emergencia',
            name='for_008_emer_paci_falt_dato',
        ),
        migrations.AddField(
            model_name='admision_datos',
            name='adm_dato_paci_falt_dato',
            field=models.IntegerField(default=0),
        ),
    ]
