# Generated by Django 5.1.1 on 2025-07-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0013_remove_form_008_emergencia_for_008_emer_paci_falt_dato_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eniuser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='eniuser',
            unique_together={('fun_tipo_iden', 'username')},
        ),
    ]
