# Generated by Django 5.1.1 on 2025-08-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0014_alter_eniuser_options_alter_eniuser_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_008_emergencia',
            name='for_008_emer_aten_fina',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
