# Generated by Django 5.1.1 on 2025-08-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0015_form_008_emergencia_for_008_emer_aten_fina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_008_emergencia',
            old_name='for_008_emer_nomb_esta_salu',
            new_name='for_008_emer_unid',
        ),
    ]
