# Generated by Django 5.1.1 on 2025-08-09 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0016_rename_for_008_emer_nomb_esta_salu_form_008_emergencia_for_008_emer_unid'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_008_emergencia',
            name='eniUser',
            field=models.ForeignKey(blank=True, help_text='ID de usuario que registra la atencion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_008_emergencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='form_008_emergencia',
            name='admision_datos',
            field=models.IntegerField(blank=True, help_text='ID de admision de datos del paciente', null=True),
        ),
    ]
