# Generated by Django 5.1.1 on 2025-08-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0018_alter_form_008_emergencia_for_008_emer_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_008_emergencia',
            name='for_008_emer_edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='form_008_emergencia',
            name='for_008_emer_edad_gest',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Edad gestacional en semanas (ej: 38.5)', max_digits=4),
        ),
    ]
