# Generated by Django 5.1.1 on 2025-09-01 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0020_alter_form_008_emergencia_for_008_emer_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_barr_sect',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_call_prin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_call_secu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_resi_refe_resi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='form_008_emergencia',
            name='for_008_emer_dire_domi',
            field=models.CharField(blank=True, max_length=460),
        ),
        migrations.CreateModel(
            name='agenda_diagnostico_imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_diag_imag_unid_salu', models.CharField(blank=True, max_length=120)),
                ('age_diag_imag_tipo_docu_iden', models.CharField(blank=True, max_length=25)),
                ('age_diag_imag_nume_iden', models.CharField(blank=True, max_length=25)),
                ('age_diag_imag_apel', models.CharField(blank=True, max_length=80)),
                ('age_diag_imag_nomb', models.CharField(blank=True, max_length=80)),
                ('age_diag_imag_sexo', models.CharField(blank=True, max_length=15)),
                ('age_diag_imag_fech_naci', models.DateField(blank=True, null=True)),
                ('age_diag_imag_tele', models.CharField(blank=True, max_length=15)),
                ('age_diag_imag_corr', models.CharField(blank=True, max_length=40)),
                ('age_diag_imag_dire', models.CharField(blank=True, max_length=460)),
                ('age_diag_imag_fech_cita', models.DateField(blank=True, null=True)),
                ('age_diag_imag_hora_cita', models.TimeField(blank=True, null=True)),
                ('age_diag_imag_esta_cita', models.IntegerField(blank=True, null=True)),
                ('age_diag_imag_tipo_serv', models.CharField(blank=True, max_length=20)),
                ('age_diag_imag_prof_agen_cita', models.CharField(blank=True, max_length=105)),
                ('age_diag_imag_obse', models.CharField(blank=True, max_length=350)),
                ('admision_datos', models.IntegerField(blank=True, help_text='ID de admision de datos del paciente', null=True)),
                ('eniUser', models.ForeignKey(blank=True, help_text='ID de usuario que registra la atencion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_diagnostico_imagen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
