# Generated by Django 5.1.1 on 2025-09-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0021_alter_admision_datos_adm_dato_resi_barr_sect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_008_emergencia',
            name='for_008_emer_obse',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
