# Generated by Django 5.2.7 on 2025-10-26 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0022_alter_form_008_emergencia_for_008_emer_obse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_008_emergencia',
            name='admision_datos',
            field=models.IntegerField(blank=True, help_text='ID de admision de datos del paciente del formulario 008 emergencia', null=True),
        ),
        migrations.AlterField(
            model_name='form_008_emergencia',
            name='eniUser',
            field=models.ForeignKey(blank=True, help_text='ID de usuario que registra la atencion formulario 008 emergencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_008_emergencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='agenda_turno_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_turn_paci_unid_salu', models.CharField(blank=True, max_length=120)),
                ('age_turn_paci_tipo_docu_iden', models.CharField(blank=True, max_length=25)),
                ('age_turn_paci_nume_iden', models.CharField(blank=True, max_length=25)),
                ('age_turn_paci_apel', models.CharField(blank=True, max_length=80)),
                ('age_turn_paci_nomb', models.CharField(blank=True, max_length=80)),
                ('age_turn_paci_sexo', models.CharField(blank=True, max_length=15)),
                ('age_turn_paci_fech_naci', models.DateField(blank=True, null=True)),
                ('age_turn_paci_tele', models.CharField(blank=True, max_length=15)),
                ('age_turn_paci_corr', models.CharField(blank=True, max_length=40)),
                ('age_turn_paci_dire', models.CharField(blank=True, max_length=460)),
                ('age_turn_paci_unid_salu_resp_segu_aten', models.CharField(blank=True, max_length=100)),
                ('age_turn_paci_obse', models.CharField(blank=True, max_length=350)),
                ('admision_datos', models.IntegerField(blank=True, help_text='ID de admision de datos del paciente de agenda de turno paciente', null=True)),
                ('eniUser', models.ForeignKey(blank=True, help_text='ID de usuario que registra la atencion de agenda de turno paciente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_diagnostico_imagen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='admin_agenda_turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_agen_turn_fech', models.DateField(blank=True, null=True)),
                ('adm_agen_turn_tipo_espe', models.CharField(blank=True, max_length=100)),
                ('adm_agen_turn_prof_cita', models.CharField(blank=True, max_length=100)),
                ('adm_agen_turn_hora_inic', models.TimeField(blank=True, null=True)),
                ('adm_agen_turn_hora_fin', models.TimeField(blank=True, null=True)),
                ('adm_agen_turn_esta_cita', models.IntegerField(blank=True, null=True)),
                ('eniUser', models.IntegerField(blank=True, help_text='ID de usuario que registra la agenda de turno de paciente', null=True)),
                ('agenda_turno_paciente', models.ForeignKey(blank=True, help_text='ID de agenda de turno de paciente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_diagnostico_imagen', to='eni.agenda_turno_paciente')),
            ],
        ),
        migrations.DeleteModel(
            name='agenda_diagnostico_imagen',
        ),
    ]
