# Generated by Django 5.2.7 on 2026-03-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0023_alter_form_008_emergencia_admision_datos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_agenda_turnos',
            name='adm_agen_turn_dura_cita',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
