# Generated by Django 5.2.7 on 2026-03-03 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0024_admin_agenda_turnos_adm_agen_turn_dura_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_agenda_turnos',
            name='agenda_turno_paciente',
        ),
        migrations.AddField(
            model_name='admin_agenda_turnos',
            name='adm_agen_turn_apel_nomb_paci',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='admin_agenda_turnos',
            name='adm_agen_turn_corr',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='admin_agenda_turnos',
            name='adm_agen_turn_dire',
            field=models.CharField(blank=True, max_length=460),
        ),
        migrations.AddField(
            model_name='admin_agenda_turnos',
            name='adm_agen_turn_nume_iden_paci',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='admin_agenda_turnos',
            name='adm_agen_turn_obse',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='admin_agenda_turnos',
            name='adm_agen_turn_tele',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='admin_agenda_turnos',
            name='adm_agen_turn_unid_salu_resp_segu_aten',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admin_agenda_turnos',
            name='id_prof_cita',
            field=models.IntegerField(blank=True, help_text='ID de profesional que hara la atencion', null=True),
        ),
        migrations.AlterField(
            model_name='admin_agenda_turnos',
            name='eniUser',
            field=models.ForeignKey(blank=True, help_text='ID de usuario que registra la atencion de agenda de turno paciente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_diagnostico_imagen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='agenda_turno_paciente',
        ),
    ]
