# Generated by Django 5.2.7 on 2026-03-11 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0025_remove_admin_agenda_turnos_agenda_turno_paciente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_agenda_turnos',
            old_name='adm_agen_turn_corr',
            new_name='adm_agen_turn_corr_paci',
        ),
        migrations.RenameField(
            model_name='admin_agenda_turnos',
            old_name='adm_agen_turn_dire',
            new_name='adm_agen_turn_dire_paci',
        ),
        migrations.RenameField(
            model_name='admin_agenda_turnos',
            old_name='adm_agen_turn_obse',
            new_name='adm_agen_turn_obse_paci',
        ),
        migrations.RenameField(
            model_name='admin_agenda_turnos',
            old_name='adm_agen_turn_tele',
            new_name='adm_agen_turn_tele_paci',
        ),
        migrations.RenameField(
            model_name='admin_agenda_turnos',
            old_name='adm_agen_turn_unid_salu_resp_segu_aten',
            new_name='adm_agen_turn_unid_salu_resp_segu_aten_paci',
        ),
        migrations.AddField(
            model_name='admin_agenda_turnos',
            name='adm_agen_turn_tipo_iden_paci',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='admin_agenda_turnos',
            name='eniUser',
            field=models.ForeignKey(blank=True, help_text='ID de usuario que registra el turno para el paciente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_diagnostico_imagen', to=settings.AUTH_USER_MODEL),
        ),
    ]
