# Generated by Django 5.2.7 on 2026-03-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0026_rename_adm_agen_turn_corr_admin_agenda_turnos_adm_agen_turn_corr_paci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_agenda_turnos',
            name='id_admi_paci',
            field=models.IntegerField(blank=True, help_text='ID de paciente registrado en admision de datos', null=True),
        ),
    ]
