# Generated by Django 5.2.7 on 2026-03-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0027_admin_agenda_turnos_id_admi_paci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_agenda_turnos',
            name='adm_agen_turn_obse_paci',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
