# Generated by Django 5.2.7 on 2026-03-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0028_alter_admin_agenda_turnos_adm_agen_turn_obse_paci'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_agenda_turnos',
            name='adm_agen_turn_unid_salu',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
