# Generated by Django 5.2.7 on 2026-03-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0029_admin_agenda_turnos_adm_agen_turn_unid_salu'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_agenda_turnos',
            name='adm_agen_turn_rese_unic_salu',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
