# Generated by Django 5.2.7 on 2026-04-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0030_admin_agenda_turnos_adm_agen_turn_rese_unic_salu'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_agenda_turnos',
            name='adm_agen_turn_cons_link_paci',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='admin_agenda_turnos',
            name='adm_agen_turn_cons_obse_paci',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
