# Generated by Django 5.2.7 on 2026-05-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0031_admin_agenda_turnos_adm_agen_turn_cons_link_paci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_agenda_turnos',
            name='adm_agen_turn_cons_tipo_serv',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
