# Generated by Django 5.2.7 on 2026-05-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0032_admin_agenda_turnos_adm_agen_turn_cons_tipo_serv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influenza',
            name='eniUser',
        ),
        migrations.RemoveField(
            model_name='registro_vacunado',
            name='eniUser',
        ),
        migrations.RemoveField(
            model_name='reporte_eni',
            name='eniUser',
        ),
        migrations.RemoveField(
            model_name='tardio',
            name='eniUser',
        ),
        migrations.RemoveField(
            model_name='temprano',
            name='eniUser',
        ),
        migrations.AlterField(
            model_name='admin_agenda_turnos',
            name='adm_agen_turn_tipo_iden_paci',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_pers_tipo_iden',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admision_datos',
            name='adm_dato_repr_tipo_iden',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='eniuser',
            name='fun_tipo_iden',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.DeleteModel(
            name='desperdicio',
        ),
        migrations.DeleteModel(
            name='influenza',
        ),
        migrations.DeleteModel(
            name='registro_vacunado',
        ),
        migrations.DeleteModel(
            name='reporte_eni',
        ),
        migrations.DeleteModel(
            name='tardio',
        ),
        migrations.DeleteModel(
            name='temprano',
        ),
    ]
