# Generated by Django 5.2.7 on 2026-05-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0033_remove_influenza_eniuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_008_emergencia',
            name='for_008_emer_tipo_docu_iden',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
