# Generated by Django 5.2.7 on 2026-05-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0034_alter_form_008_emergencia_for_008_emer_tipo_docu_iden'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_008_emergencia',
            name='for_008_emer_caus_aten',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='form_008_emergencia',
            name='for_008_emer_nomb_hosp_refe_hosp',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
