# Generated by Django 5.2.7 on 2026-05-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eni', '0035_form_008_emergencia_for_008_emer_caus_aten_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_008_emergencia',
            name='for_008_emer_fech_naci_paci',
            field=models.DateField(blank=True, null=True),
        ),
    ]
